const DEFAULT_REFERRAL_SERVICE_STATUS = 'Routine'
const EMERGENCY_REFERRAL_SERVICE_STATUS = 'Emergency'
const DEFAULT_REFERRAL_STATUS = 'Active'

export {
  DEFAULT_REFERRAL_SERVICE_STATUS,
  EMERGENCY_REFERRAL_SERVICE_STATUS,
  DEFAULT_REFERRAL_STATUS,
}
