environment: ""
image:
  repository: ''
  pullPolicy: Always
  tag: ''

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}

podAnnotations:
  config.linkerd.io/proxy-cpu-limit: "1"
  config.linkerd.io/proxy-cpu-request: "70m"
  config.linkerd.io/proxy-memory-limit: "1Gi"
  config.linkerd.io/proxy-memory-request: "8Mi"

podSecurityContext: {}

securityContext: 
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  runAsGroup: 1001
  runAsNonRoot: true
  runAsUser: 1001
  seccompProfile:
    type: RuntimeDefault

container:
  portName: http
  containerPort: 3004
  protocol: TCP

service:
  enabled: true
  type: ClusterIP
  port: 3004

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
  hosts:
  - host: ui.integration.psychplus.dev
    paths:
    - path: /ehr
      pathType: Prefix
  tls:
  - hosts:
    - ui.integration.psychplus.dev
    secretName: ui-psychplus-io-tls

ingressAuth:
  enabled: false

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 800m
    memory: 1500Mi
  requests:
    cpu: 500m
    memory: 900Mi

behavior:
  scaleDown:
    stabilizationWindowSeconds: 3600
    policies:
      - type: Pods
        value: 1
        periodSeconds: 1800
  scaleUp:
    stabilizationWindowSeconds: 60
    policies:
      - type: Pods
        value: 2
        periodSeconds: 60

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 30
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 80

startupProbeEnabled: true
startupProbe:
  httpGet:
    path: /ehr/healthz/liveness_120C4006-918E-4934-B701-D6F6ACC097FB
    port: http
  periodSeconds: 30
  timeoutSeconds: 30

livenessProbeEnabled: true
livenessProbe:
  httpGet:
    path: /ehr/healthz/liveness_120C4006-918E-4934-B701-D6F6ACC097FB
    port: http
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbeEnabled: true
readinessProbe:
  httpGet:
    path: /ehr/healthz/readiness_120C4006-918E-4934-B701-D6F6ACC097FB
    port: http
  periodSeconds: 10
  timeoutSeconds: 1

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodepool
          operator: NotIn
          values:
          - system

env:
  - name: APP_CODE
    value: "p+galaxy-ui"

  - name: APP_PATH
    value: "ehr"

  - name: APP_VERSION
    value: "1.0.0"

#global-values-replace-tag
