export const valueMapping: Record<string, string[]> = {
  general: [
    'gnNormal',
    'gnFatigue',
    'gnFever',
    'gnWeightLoss',
    'gnDiaphoresis',
    'gnOther',
  ],
  skin: [
    'sknNormal',
    'sknPersistentRashSpots',
    'sknAcne',
    'sknTattoos',
    'sknOther',
  ],
  heent: [
    'hntNormal',
    'hntHeadache',
    'hntTmjPain',
    'hntVisualHearingProblems',
    'hntRhinitis',
    'hntSoreThroat',
    'hntFrequentNoseBleeds',
    'hntPerrla',
    'hntNaresArePatentWithoutDrainage',
    'hntOther',
  ],
  neck: ['nkNormal', 'nkMasses', 'nkOther'],
  lymphNodes: ['lnNormal', 'lnNonePalpated', 'lnOther'],
  chest: [
    'chsNormal',
    'chsChronicCough',
    'chsWheezing',
    'chsDoeDyspneaOnExertion',
    'chsChestPain',
    'chsBreastLumpsDischarge',
    'chsOther',
  ],
  cardiovascularCvs: [
    'cvsNormal',
    'cvsMurmurs',
    'cvsHypertensionHtn',
    'cvsOther',
  ],
  lungs: ['lngNormal', 'lngClearToAuscultationBilaterally', 'lngOther'],
  gastrointestinalGi: [
    'giNormal',
    'giAbdominalPain',
    'giVomiting',
    'giDiarrheaConstipation',
    'giJaundice',
    'giFoodIntolerance',
    'giOther',
  ],
  gynecologicalGyn: [
    'gynNormal',
    'gynCycleLength',
    'gynFlow',
    'gynDysmenorrhea',
    'gynVaginalDischarge',
    'gynDyspareunia',
    'gynOther',
  ],
  genitourinaryGu: [
    'guNormal',
    'guDysuria',
    'guDischarge',
    'guScrotalMasses',
    'guUrinaryFrequency',
    'guIncontinence',
    'guEnuresis',
    'guOther',
  ],
  centralNervousSystemCns: [
    'cnsNormal',
    'cnsFainting',
    'cnsLossOfConsciousnessLoc',
    'cnsWeakness',
    'cnsTremor',
    'cnsSeizures',
    'cnsOther',
  ],
  musculoskeletal: [
    'msuNormal',
    'msuScoliosis',
    'msuJointAchesSwelling',
    'msuRecentTrauma',
    'msuLimp',
    'msuSportsInjury',
    'msuAcuteDeformity',
    'msuClubbingCyanosisEdema',
    'msuTender',
    'msuRomRestrictions',
    'msuOther',
  ],
  nutrition: [
    'nutNormal',
    'nutUsualEatingHabits',
    'nutCurrentlyDieting',
    'nutBinges',
    'nutDietPills',
    'nutBodyImage',
    'nutOther',
  ],
  psychiatric: [
    'psyNormal',
    'psyDepression',
    'psySuicideContemplatedAttempted',
    'psyHallucinations',
    'psyPreviousPsychologicalIssues',
    'psyOther',
  ],
  cranialNervesExam: [
    'cneOlfactory',
    'cneOlfactoryNormal',
    'cneOlfactoryAbnormal',
    'cneOptical',
    'cneOpticalNormal',
    'cneOpticalAbnormal',
    'cneTrochlear',
    'cneTrochlearNormal',
    'cneTrochlearAbnormal',
    'cneTrigeminal',
    'cneTrigeminalNormal',
    'cneTrigeminalAbnormal',
    'cneAbducens',
    'cneAbducensNormal',
    'cneAbducensAbnormal',
    'cneFacial',
    'cneFacialNormal',
    'cneFacialAbnormal',
    'cneAuditory',
    'cneAuditoryNormal',
    'cneAuditoryAbnormal',
    'cneGlossopharyngeal',
    'cneGlossopharyngealNormal',
    'cneGlossopharyngealAbnormal',
    'cneVagus',
    'cneVagusNormal',
    'cneVagusAbnormal',
    'cneSpinalAccessory',
    'cneSpinalAccessoryNormal',
    'cneSpinalAccessoryAbnormal',
    'cneHypoglossal',
    'cneHypoglossalNormal',
    'cneHypoglossalAbnormal',
    'cneOther',
  ],
}

export function updateToNormalOrAbnormal(values: string[] | null): string[] {
  const result = values?.map((value) => {
    const lowerCaseValue = value.toLowerCase()
    if (lowerCaseValue.includes('abnormal')) {
      return 'Abnormal'
    } else if (lowerCaseValue.includes('normal')) {
      return 'Normal'
    }
    return value
  })
  return result || []
}
