const getInitialValues = () => ({
  psychHospitalizations: 0,
  suicideAttempts: 0,
  depression: undefined,
  depressionAge: undefined,
  anxiety: undefined,
  anxietyAge: undefined,
  schizophrenia: undefined,
  schizophreniaAge: undefined,
  bipolar: undefined,
  bipolarAge: undefined,
  disorder: undefined,
  disorderAge: undefined,
  obsessiveThinking: undefined,
  obsessiveThinkingAge: undefined,
  compulsiveBehavior: undefined,
  compulsiveBehaviorAge: undefined,
  adhd: undefined,
  adhdAge: undefined,
  autism: undefined,
  autismAge: undefined,
  eatingDisorder: undefined,
  eatingDisorderAge: undefined,
  exposureToTrauma: undefined,
  exposureToTraumaAge: undefined,
  cuttingSelfHarmBehavior: undefined,
  cuttingSelfHarmBehaviorAge: undefined,
  problemsWithSleep: undefined,
  problemsWithSleepAge: undefined,
  panicAttacks: undefined,
  panicAttacksAge: undefined,
  dementia: undefined,
  dementiaAge: undefined,
  personalityDisorder: undefined,
  personalityDisorderAge: undefined,
  intellectualDisability: undefined,
  intellectualDisabilityAge: undefined,
  other: undefined,
  otherDetails: undefined,
})

export { getInitialValues }
