
const defaultValues = {
  startingDate: undefined,
  endingDate: undefined,
  name: '',
  age: [],
  gender: '',
  dateOfBirth: undefined,
  patientStatuses: '',
  locationIds: '',
  servicesOffered: [],
  providerType: '',
  unitId: '',
  roomId: '',
  groupId: '',
  primaryInsuranceName: '',
  secondaryInsuranceName: '',
  visitType: '',
  visitSequence: '',
  visitMedium: '',
  appointmentStatuses: [],
  patientInsuranceVerificationStatus: '',
  diagnosisCode: '',
  cptCode: '',
  dateOfAdmissionStart: undefined,
  dateOfAdmissionEnd: undefined,
  lengthOfStayMin: null,
  lengthOfStayMax: null,
  lastCoverageDateStart: undefined,
  lastCoverageDateEnd: undefined,
  legalStatus: '',
  copayDueMin: null,
  copayDueMax: null,
  coInsuranceDueMin: null,
  coInsuranceDueMax: null,
  balanceDueMin: null,
  balanceDueMax: null,
  noteSignedStatus: '',
  facilityAdmissionIds: '',
}

export { defaultValues }
