version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - 8080:80
    networks:
      - psychplus
  platform:
    container_name: platform
    build:
      context: .
      dockerfile: ./apps/platform/Dockerfile
    environment:
      - API_URL=https://api-pr-2000.ode.psychplus.dev
      - CLINICAL_URL=http://localhost:8001
      - PATIENT_URL=http://localhost:8002
      - REVCYCLE_URL=http://localhost:8003
      - LOGIN_ENDPOINT=http://api:80/api/login
      - MOCK_API_URL=http://api:8080
    ports:
      - 8000:3000
    networks:
      - psychplus
  clinical:
    container_name: clinical
    build:
      context: .
      dockerfile: ./apps/clinical/Dockerfile
    environment:
      - API_URL=https://api-pr-2000.ode.psychplus.dev
      - CLINICAL_URL=http://localhost:8001
      - PATIENT_URL=http://localhost:8002
      - REVCYCLE_URL=http://localhost:8003
      - LOGIN_ENDPOINT=http://api:80/api/login
      - MOCK_API_URL=http://api:8080
    ports:
      - 8001:3000
    networks:
      - psychplus
  patient:
    container_name: patient
    build:
      context: .
      dockerfile: ./apps/patient/Dockerfile
    environment:
      - API_URL=https://api-pr-2000.ode.psychplus.dev
      - CLINICAL_URL=http://localhost:8001
      - PATIENT_URL=http://localhost:8002
      - REVCYCLE_URL=http://localhost:8003
      - LOGIN_ENDPOINT=http://api:80/api/login
      - MOCK_API_URL=http://api:8080
    ports:
      - 8002:3000
    networks:
      - psychplus
  revcycle:
    container_name: revcycle
    build:
      context: .
      dockerfile: ./apps/revcycle/Dockerfile
    environment:
      - API_URL=https://api-pr-2000.ode.psychplus.dev
      - CLINICAL_URL=http://localhost:8001
      - PATIENT_URL=http://localhost:8002
      - REVCYCLE_URL=http://localhost:8003
      - LOGIN_ENDPOINT=http://api:80/api/login
      - MOCK_API_URL=http://api:8080
    ports:
      - 8003:3000
    networks:
      - psychplus

networks:
  psychplus:
