version: '3'

services:
  galaxy:
    container_name: galaxy
    build:
      context: .
      dockerfile: ./apps/galaxy/Dockerfile
    environment:
      - APP_CODE=p+galaxy-ui
      - APP_PATH=galaxy
      - APP_VERSION=1.0.0
      - APP_ENV=development
      - PATIENT_URL=http://localhost:8002
      - CLINICAL_URL=http://localhost:8001
      - REVCYCLE_URL=http://localhost:8003
      - PLATFORM_URL=http://localhost:8000
      - API_URL=https://api-pr-2000.ode.psychplus.dev
      - LOGIN_ENDPOINT=https://auth-pr-2000.ode.psychplus.dev/login
    ports:
      - 8001:3001
    networks:
      - psychplus

  patient:
    container_name: patient
    build:
      context: .
      dockerfile: ./apps/patient/Dockerfile
      args:
        - DISABLE_APP_PATH=true
    environment:
      - APP_CODE=p+patient-ui
      - APP_PATH=
      - APP_VERSION=1.0.0
      - APP_ENV=development
      - PATIENT_URL=http://localhost:8002
      - CLINICAL_URL=http://localhost:8001
      - REVCYCLE_URL=http://localhost:8003
      - PLATFORM_URL=http://localhost:8000
      - API_URL=https://api-pr-2000.ode.psychplus.dev
      - SERVICE_TO_SERVICE_AUTH_URL=https://auth-pr-2000.ode.psychplus.dev
      - SERVICE_TO_SERVICE_API_URL=https://api-pr-2000.ode.psychplus.dev
      - LOGIN_ENDPOINT=https://auth-pr-2000.ode.psychplus.dev/login
    ports:
      - 8002:3000
    networks:
      - psychplus

networks:
  psychplus:
