version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - 8080:80
    networks:
      - psychplus
  platform:
    container_name: platform
    build:
      context: .
      dockerfile: ./apps/platform/Dockerfile
    environment:
      - CLINICAL_URL=http://localhost:8001
      - PATIENT_URL=http://localhost:8002
      - REVCYCLE_URL=http://localhost:8003
      - LOGIN_ENDPOINT=http://api:80/api/login
    ports:
      - 4000:80
    networks:
      - psychplus
  patient:
    container_name: patient
    build:
      context: .
      dockerfile: ./apps/patient/Dockerfile
    environment:
      - API_URL=http://api:80
      - LOGIN_ENDPOINT=http://api:80/api/login
    ports:
      - 3001:80
    networks:
      - psychplus
  clinical:
    container_name: clinical
    build:
      context: .
      dockerfile: ./apps/clinical/Dockerfile
    environment:
      - API_URL=http://api:80
      - LOGIN_ENDPOINT=http://localhost:8080/api/login
    ports:
      - 8000:80
    networks:
      - psychplus
  revcycle:
    container_name: revcycle
    build:
      context: .
      dockerfile: ./apps/revcycle/Dockerfile
    environment:
      - API_URL=http://api:80
    ports:
      - 8001:80
    networks:
      - psychplus

networks:
  psychplus:
