version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - 8080:80
    networks:
      - psychplus
  platform:
    container_name: platform
    build:
      context: .
      dockerfile: ./apps/platform/Dockerfile
    environment:
      - CLINICAL_URL=http://localhost:3002
      - REVCYCLE_URL=http://localhost:3003
      - LOGIN_ENDPOINT=http://api:80/api/login
    ports:
      - 3000:80
    networks:
      - psychplus
  ehr:
    container_name: ehr
    build:
      context: .
      dockerfile: ./apps/ehr/Dockerfile
    environment:
      - API_URL=http://api:80
      - CLINICAL_URL=http://localhost:3002
      - REVCYCLE_URL=http://localhost:3003
      - LOGIN_ENDPOINT=http://api:80/api/login
    ports:
      - 3001:80
    networks:
      - psychplus
  clinical:
    container_name: clinical
    build:
      context: .
      dockerfile: ./apps/clinical/Dockerfile
    environment:
      - API_URL=http://api:80
    ports:
      - 3002:80
    networks:
      - psychplus
  revcycle:
    container_name: revcycle
    build:
      context: .
      dockerfile: ./apps/revcycle/Dockerfile
    environment:
      - API_URL=http://api:80
    ports:
      - 3003:80
    networks:
      - psychplus

networks:
  psychplus:
