const SUBMITTER_LIST_TABLE_PAGE_SIZE = 20
const RECEIVER_LIST_TABLE_PAGE_SIZE = 20
const EDI_LIST_TABLE_PAGE_SIZE = 20

export {
  SUBMITTER_LIST_TABLE_PAGE_SIZE,
  RECEIVER_LIST_TABLE_PAGE_SIZE,
  EDI_LIST_TABLE_PAGE_SIZE,
}
