const getDefaultValues = (providerId?: string) => ({
  startingDate: undefined,
  endingDate: undefined,
  bookedAppointmentTime: undefined,
  name: '',
  age: null,
  gender: '',
  dateOfBirth: undefined,
  patientStatuses: [],
  stateIds: [],
  locationIds: [],
  serviceIds: [],
  providerTypes: [],
  providerIds: providerId ? [providerId]: [],
  unitIds: [],
  roomIds: [],
  groupIds: [],
  primaryInsuranceNames: [],
  secondaryInsuranceNames: [],
  visitTypes: [],
  visitSequences: [],
  visitMediums: [],
  appointmentStatuses: [],
  patientInsuranceVerificationStatuses: [],
  diagnosisCode: '',
  insuranceAuthorizationNumber: '',
  cptCode: '',
  dateOfAdmissionStart: undefined,
  dateOfAdmissionEnd: undefined,
  lengthOfStayMin: null,
  lengthOfStayMax: null,
  lastCoverageDateStart: undefined,
  lastCoverageDateEnd: undefined,
  legalStatuses: [],
  copayDueMin: null,
  copayDueMax: null,
  copayPaid: null,
  coInsuranceDueMin: null,
  coInsuranceDueMax: null,
  coInsurancePaid: null,
  balanceDueMin: null,
  balanceDueMax: null,
  balancePaid: null,
  noteSignedStatuses: [],
})

export { getDefaultValues }