const CODE_RACE = '1000-9'
const CODE_ETHNICITY = '2133-7'
const RACES_GROUPING_CODES = ['R', 'R1', 'R2', 'R3', 'R4', 'R5']
const ETHNICITIES_GROUPING_CODES = ['E', 'E1', 'E2']
const CODE_NOT_SET = 'NotSet'
const CODE_NOT_USED = 'NotUsed'
const HOSPITAL_SERVICE_GROUP = ['Hospital']

const CODESETS = {
  Gender: 'Gender',
  CustomerStatus: 'CustomerStatus',
  GenderOrientation: 'GenderOrientation',
  GenderExpression: 'GenderExpression',
  GenderPronoun: 'GenderPronoun',
  Language: 'Language',
  SpecialistType: 'SpecialistType',
  ProviderType: 'ProviderType',
  AppointmentType: 'AppointmentType',
  VisitSequenceType: 'VisitSequenceType',
  VisitRepeatFrequency: 'VisitRepeatFrequency',
  AdmissionLegalStatus: 'AdmissionLegalStatus',
  RaceAndEthnicity: 'cdc.PH_RaceAndEthnicity_CDC',
  ProfSuffix: 'HL7v2.Degree',
  StaffRole: 'StaffRole',
  UserRoleEnum: 'UserRoleEnum',
  LanguageAbility: 'HL7v3.LanguageAbilityMode',
  LanguageProficiency: 'HL7v3.LanguageAbilityProficiency',
  Religion: 'HL7v3.ReligiousAffiliation',
  CommonLanguages: 'FHIR.CommonLanguages',
  VisitMedium: 'AppointmentType',
  ServicesOffered: 'ServicesOffered',
  ResourceStatus: 'ResourceStatus',
  AppointmentStatus: 'AppointmentStatus',
  EncounterType: 'EncounterType',
  NotificationStatus: 'NotificationStatusType',
  NotificationChannel: 'NotificationChannel',
  Relationship: 'HL7v3.RoleCode',
  InsurancePolicyPriority: 'InsurancePolicyPriority',
  InsuranceRelationship: 'InsuranceRelationship',
  GuardianRelationship: 'GuardianRelationship',
  VacationStatus: 'VacationStatus',
  VerificationStatus: 'VerificationStatus',
  BillingVerificationStatus: 'BillingVerificationStatus',
  VisitSequence: 'VisitSequenceType',
  LegalStatus: 'AdmissionLegalStatus',
  TransactionType: 'TransactionType',
  FeeScheduleCategoryType: 'FeeScheduleCategory',
  PatientConsentPolicyType: 'PatientConsentPolicyType',
  ClaimFiltrationDateType: 'ClaimFiltrationDateType',
  RecordStatus: 'RecordStatus',
  PaymentSourceType: 'PaymentSourceType',
  PaymentMethod: 'PaymentMethod',
  PaymentResponsibility: 'PaymentResponsibility',
  QueryByNextDays: 'QueryByNextDays',
  AccidentType: 'AccidentType',
  LocationType: 'LocationType',
  ContactMadeStatus: 'ContactMadeStatus',
  ReferralSource: 'ReferralSource',
  ParameterAdjustmentStatus: 'ParameterAdjustmentStatus',
  LicenseStatus: 'LicenseStatus',

  // PsychPlusPublic Codesets
  TMSCoilType: 'PsychPlusPublic.TMSCoilType',
  TMSStimulationSite: 'PsychPlusPublic.TMSStimulationSite',
  ProviderAttributions: 'PsychPlusPublic.ProviderAttributions',
  ProcessedAsCode: 'ProcessedAsCode',
  AdjustmentGroupCode: 'AdjustmentGroupCode',
  PaymentPostingStatus: 'PaymentPostingStatus',
  ServicesStatus: 'ServicesStatus',
  VisitType: 'PsychPlusPublic.VisitType',
  FirstResponder: 'psychpluspublic.FirstResponderOccupation',
  UsStates: 'PsychPlusPublic.UsStates',
  PlaceOfSerivce: 'PsychPlusPublic.PlaceOfService',
  GroupTherapyType: 'PsychPlusPublic.GroupTherapyType',
  DescriptionTransference: 'PsychPlusPublic.DescriptionTransference',
  PsychoanalyticTechnique: 'PsychPlusPublic.PsychoanalyticTechnique',
  TherapyModality: 'PsychPlusPublic.TherapyModality',
  TherapyIntervention: 'PsychPlusPublic.TherapyIntervention',
  PractitionerHonor: 'PsychPlusPublic.PractitionerHonor',
  ClaimStatus: 'PsychPlusPublic.ClaimStatus',
  QueryByLastDays: 'QueryByLastDays',
  NoteSignatureStatus: 'NoteSignatureStatus',
  ServiceLevelType: 'ServiceLevelType',
  PayerType: 'PayerType',
  AbnormalFlag: 'HL7v2.AbnormalFlags',
  StatusCodes: 'HL7v2.ObservationResultStatusCodes',
  Unit: 'CDC.PHVS_UnitofMeasure_TB',
  PaymentDateType: 'PaymentDateType',
  NoteType: 'PsychPlusPublic.NoteType',
  NoteTitle: 'PsychPlusPublic.NoteTitle',
  LabOrderStatus: 'LabOrderStatus',
  LabBillingType: 'LabBillingType',
  SpecimenType: 'HL7v2.SpecimenType',
  SpecimenRole: 'HL7v2.SpecimenRole',
  SpecimentAdditive: 'HL7v2.SpecimentAdditive',
  SpecimenCollectionMethod: 'HL7v2.SpecimenCollectionMethod',
}
export {
  CODESETS,
  CODE_ETHNICITY,
  CODE_RACE,
  ETHNICITIES_GROUPING_CODES,
  RACES_GROUPING_CODES,
  CODE_NOT_SET,
  HOSPITAL_SERVICE_GROUP,
  CODE_NOT_USED,
}
