const CODE_RACE = '1000-9'
const CODE_ETHNICITY = '2133-7'
const RACES_GROUPING_CODES = ['R', 'R1', 'R2', 'R3', 'R4', 'R5']
const ETHNICITIES_GROUPING_CODES = ['E', 'E1', 'E2']

const CODESETS = {
  UsStates: 'PsychPlusPublic.UsStates',
  Gender: 'Gender',
  CustomerStatus: 'CustomerStatus',
  GenderOrientation: 'GenderOrientation',
  GenderExpression: 'GenderExpression',
  GenderPronoun: 'GenderPronoun',
  Language: 'Language',
  SpecialistType: 'SpecialistType',
  ProviderType: 'ProviderType',
  FacilityAppointmentStatus: 'FacilityAppointmentStatus',
  AppointmentType: 'AppointmentType',
  VisitSequenceType: 'VisitSequenceType',
  VisitRepeatFrequency: 'VisitRepeatFrequency',
  AdmissionLegalStatus: 'AdmissionLegalStatus',
  RaceAndEthnicity: 'cdc.PH_RaceAndEthnicity_CDC',
  ProfSuffix: 'HL7v2.Degree',
  LanguageAbility: 'HL7v3.LanguageAbilityMode',
  LanguageProficiency: 'HL7v3.LanguageAbilityProficiency',
  Religion: 'HL7v3.ReligiousAffiliation',
  GroupTherapyType: 'PsychPlusPublic.GroupTherapyType',
  CommonLanguages: 'FHIR.CommonLanguages',
  FirstResponder: 'psychpluspublic.FirstResponderOccupation',
  VisitMedium: 'AppointmentType',
  ServicesOffered: 'ServicesOffered',
  AppointmentStatus: 'AppointmentStatus',
  EncounterType: 'EncounterType',
  NotificationStatus: 'NotificationStatusType',
  NotificationChannel: 'NotificationChannel',
  Relationship: 'HL7v3.RoleCode',
  InsurancePolicyPriority: 'InsurancePolicyPriority',
  InsuranceRelationship: 'InsuranceRelationship',
  GuardianRelationship: 'GuardianRelationship',
  VacationStatus: 'VacationStatus',
  VisitStatus: 'FacilityAppointmentStatus',
  VerificationStatus: 'VerificationStatus',
  VisitSequence: 'VisitSequenceType',
  LegalStatus: 'AdmissionLegalStatus',
  TransactionType: 'TransactionType',
  PractitionerHonor: 'PsychPlusPublic.PractitionerHonor',
  PatientConsentPolicyType: 'PatientConsentPolicyType',
  ClaimFiltrationDateType: 'ClaimFiltrationDateType',
  RecordStatus: 'RecordStatus',
  PaymentSourceType: 'PaymentSourceType',
  PaymentMethod: 'PaymentMethod',
  VisitType: 'PsychPlusPublic.VisitType',
  PaymentResponsibility: 'PaymentResponsibility',
  QueryByNextDays: 'QueryByNextDays',
}

export {
  CODESETS,
  CODE_ETHNICITY,
  CODE_RACE,
  ETHNICITIES_GROUPING_CODES,
  RACES_GROUPING_CODES,
}
