const USER_PERMISSIONS = {
  CanViewPrescriber: 'CanViewPrescriber',
  CanViewScribe: 'CanViewScribe',
  CanViewNote: 'CanViewNote',
  CanViewMedication: 'CanViewMedication',
  CanViewScheduling: 'CanViewScheduling',
  CanViewPtVerify: 'CanViewPtVerify',
  CanViewPtVerifyAppt: 'CanViewPtVerifyAppt',
  CanViewSSN: 'CanViewSSN',
  CanViewCopay: 'CanViewCopay',
  CanViewBalance: 'CanViewBalance',
  CanViewCare: 'CanViewCare',
  CanViewMedicationPharmacy: 'CanViewMedicationPharmacy',
  CanViewRefunds: 'CanViewRefunds',
  CanViewPatient: 'CanViewPatient',
  CanViewStaff: 'CanViewStaff',
  CanViewProvider: 'CanViewProvider',
  CanViewStatus: 'CanViewStatus',
  CanViewTestPt: 'CanViewTestPt',
  CanViewTest: 'CanViewTest',
  CanViewSlot: 'CanViewSlot',
  CanViewTeam: 'CanViewTeam',
  CanViewSlotOther: 'CanViewSlotOther',
  CanShowManagement: 'CanShowManagement',
  CanChangeVisit: 'CanChangeVisit',
  CanPublicView: 'CanPublicView',
  CanViewVisitTime: 'CanViewVisitTime',
  CanViewPubVisit: 'CanViewPubVisit',
  CanViewPublicVisit: 'CanViewPublicVisit',
  CanPatientOverrideView: 'CanPatientOverrideView',
  CanAddCreditCard: 'CanAddCreditCard',
  CanPatientVacationView: 'CanPatientVacationView',
  CanViewQuicknoteUploadButton: 'CanViewQuicknoteUploadButton',
  CanScheduleUnverifiedPatients: 'CanScheduleUnverifiedPatients',
  CanViewPayerPlan: 'CanViewPayerPlan',
  CanAddPayerPlan: 'CanAddPayerPlan',
  CanEditPayerPlan: 'CanEditPayerPlan',
  CanLinkPayerPlan: 'CanLinkPayerPlan',
  CanSyncPayerPlan: 'CanSyncPayerPlan',
  CanEditTransaction: 'CanEditTransaction',
  CanDeleteTransaction: 'CanDeleteTransaction',
  CanUpdateSelfPayPatientCopayDue: 'CanUpdateSelfPayPatientCopayDue',
  CreateNewApptOfEstPatientAndViceVersa:
    'CreateNewApptOfEstPatientAndViceVersa',
  CanValidateCard: 'CanValidateCard',
}

export { USER_PERMISSIONS }
