const INITIAL_FIELDS = [
  'asthma',
  'copd',
  'htn',
  'hld',
  'dm',
  'autoimmune',
  'cad',
  'stroke',
  'migraines',
  'headInjury',
  'seizures',
  'parkinsons',
  'cirrhosis',
  'hepatitis',
  'hiv',
  'sleepApnea',
  'gerd',
  'adhdAge',
  'multipleSclerosis',
  'kidneyDisease',
  'kidneyStones',
  'hypothyroidism',
  'anemia',
  'alzheimers',
  'pregnant',
  'pregnantDate',
  'breastFeeding',
  'breastFeedingDaysPostPartum',
  'communicable',
  'measles',
  'mumps',
  'rubella',
  'chickenPox',
  'syphilis',
  'rash',
  'glaucoma',
  'chlamydias',
  'gonorrhea',
  'gastricBypass',
  'other',
  'otherDetails',
]

const getInitialValues = () =>
  Object.fromEntries(INITIAL_FIELDS.map((field) => [field, undefined]))

export { getInitialValues }
