import { TCMVisitTypes } from './types'

const TCM = [
  TCMVisitTypes.NEW_PT_TRANSITIONAL_CARE,
  TCMVisitTypes.EST_PT_TRANSITIONAL_CARE,
  TCMVisitTypes.T_NEW_PT_TRANSITIONAL_CARE,
  TCMVisitTypes.T_EST_PT_TRANSITIONAL_CARE,
]

const SCHEDULING_HISTORY_LIST_TABLE_PAGE_SIZE = 20
const FACILITY_ADMISION_ID_CHECK = '00000000-0000-0000-0000-000000000000'

export {
  TCM,
  FACILITY_ADMISION_ID_CHECK,
  SCHEDULING_HISTORY_LIST_TABLE_PAGE_SIZE,
}
