enum QuickNoteSectionName {
  QuickNoteSectionDashboard = 'QuicknoteSectionQuestionnaireDashboard',
  AddToNoteQuestionnaire = 'AddToNoteQuestionnaire',
  QuickNoteSectionDast10 = 'QuicknoteSectionQuestionnaireDast10',
  QuickNoteSectionGad7 = 'QuicknoteSectionQuestionnaireGad7',
  QuickNoteSectionPcl5 = 'QuicknoteSectionQuestionnairePcl5',
  QuickNoteSectionPhq9 = 'QuicknoteSectionQuestionnairePhq9',
  QuickNoteSectionSnapIV = 'QuicknoteSectionQuestionnaireSnapIV',
  QuickNoteSectionYbcos = 'QuicknoteSectionQuestionnaireYbocs',
  QuickNoteSectionAudit = 'QuicknoteSectionQuestionnaireAudit',
  QuickNoteSectionAims = 'QuicknoteSectionQuestionnaireAims',
  QuickNoteSectionHamD = 'QuicknoteSectionQuestionnaireHamD',
  QuickNoteSectionMoca = 'QuicknoteSectionQuestionnaireMoca',
  QuickNoteSectionDiagnosis = 'QuicknoteSectionDiagnosis',
  QuickNoteSectionHospital = 'QuicknoteSectionHospital',
  QuickNoteSectionFamilyPsychHx = 'QuicknoteSectionFamilyPsychHx',
  QuickNoteSectionPastPsychHx = 'QuicknoteSectionPastPsychHx',
  QuickNoteSectionPastMedicalHx = 'QuicknoteSectionPastMedicalHx',
  QuickNoteSectionSocialHx = 'QuicknoteSectionSocialHx',
  QuickNoteSectionSubstanceUseHx = 'QuicknoteSectionSubstanceUseHx',
  QuicknoteSectionPhysicalExam = 'QuicknoteSectionPhysicalExam',
  QuickNoteSectionPrimaryCode = 'QuicknoteSectionPrimaryCode',
  QuicknoteSectionProcedureEtcTab = 'QuicknoteSectionProcedureEtcTab',
  ProcedureTMS = 'ProcedureTMS',
  QuicknoteSectionHPI = 'QuicknoteSectionHPI',
  Addon = 'QuicknoteSectionAddOn',
  Vitals = 'QuicknoteSectionVital',
}

export { QuickNoteSectionName }
