enum QuickNoteSectionName {
  QuickNoteSectionDashboard = 'QuicknoteSectionQuestionnaireDashboard',
  AddToNoteQuestionnaire = 'AddToNoteQuestionnaire',
  QuickNoteSectionDast10 = 'QuicknoteSectionQuestionnaireDast10',
  QuickNoteSectionGad7 = 'QuicknoteSectionQuestionnaireGad7',
  QuickNoteSectionPcl5 = 'QuicknoteSectionQuestionnairePcl5',
  QuickNoteSectionPhq9 = 'QuicknoteSectionQuestionnairePhq9',
  QuickNoteSectionSnapIV = 'QuicknoteSectionQuestionnaireSnapIV',
  QuickNoteSectionYbcos = 'QuicknoteSectionQuestionnaireYbocs',
  QuickNoteSectionAudit = 'QuicknoteSectionQuestionnaireAudit',
  QuickNoteSectionAims = 'QuicknoteSectionQuestionnaireAims',
  QuickNoteSectionHamD = 'QuicknoteSectionQuestionnaireHamD',
  QuickNoteSectionMoca = 'QuicknoteSectionQuestionnaireMoca',
  QuickNoteSectionDiagnosis = 'QuicknoteSectionDiagnosis',
  QuickNoteSectionHospital = 'QuicknoteSectionHospital',
  QuickNoteSectionFamilyPsychHx = 'QuicknoteSectionFamilyPsychHx',
  QuickNoteSectionPastPsychHx = 'QuicknoteSectionPastPsychHx',
  QuickNoteSectionTherapy = 'QuicknoteSectionTherapy',
  QuickNoteSectionPastMedicalHx = 'QuicknoteSectionPastMedicalHx',
  QuickNoteSectionSocialHx = 'QuicknoteSectionSocialHx',
  QuickNoteSectionSubstanceUseHx = 'QuicknoteSectionSubstanceUseHx',
  QuicknoteSectionPhysicalExam = 'QuicknoteSectionPhysicalExam',
  QuicknoteSectionReviewOfSystem = 'QuicknoteSectionReviewOfSystem',
  QuickNoteSectionPrimaryCode = 'QuicknoteSectionPrimaryCode',
  QuicknoteSectionProcedureEtcTab = 'QuicknoteSectionProcedureEtcTab',
  ProcedureTMS = 'ProcedureTMS',
  QuicknoteSectionProcedureSpravato = 'QuicknoteSectionProcedureSpravato',
  QuicknoteSectionHPI = 'QuicknoteSectionHPI',
  Addon = 'QuicknoteSectionAddOn',
  Vitals = 'QuicknoteSectionVital',
  QuicknoteSectionMse = 'QuicknoteSectionMse',
  FollowUps = 'FollowUps',
  QuicknoteSectionPsychiatryAssessmentPlan = 'QuicknoteSectionPsychiatryAssessmentPlan',
  QuicknoteSectionTherapyAssessmentPlan = 'QuicknoteSectionTherapyAssessmentPlan',
  QuicknoteSectionFamilyInternalMedicineAssessmentPlan = 'QuicknoteSectionFamilyInternalMedicineAssessmentPlan',
}

export { QuickNoteSectionName }
