enum QuickNoteSectionName {
  QuickNoteSectionDashboard = 'QuicknoteSectionDashboard',
  QuestionnaireActualNoteView = 'QuicknoteSectionQuestionnaireActualNoteView',
  AddToNoteQuestionnaire = 'AddToNoteQuestionnaire',
  QuickNoteSectionDast10 = 'QuicknoteSectionQuestionnaireDast10',
  QuickNoteSectionGad7 = 'QuicknoteSectionQuestionnaireGad7',
  QuickNoteSectionPcl5 = 'QuicknoteSectionQuestionnairePcl5',
  QuickNoteSectionPhq9 = 'QuicknoteSectionQuestionnairePhq9',
  QuickNoteSectionSnapIV = 'QuicknoteSectionQuestionnaireSnapIV',
  QuickNoteSectionYbcos = 'QuicknoteSectionQuestionnaireYbocs',
  QuickNoteSectionAudit = 'QuicknoteSectionQuestionnaireAudit',
  QuickNoteSectionAims = 'QuicknoteSectionQuestionnaireAims',
  QuickNoteSectionHamD = 'QuicknoteSectionQuestionnaireHamD',
  QuickNoteSectionMoca = 'QuicknoteSectionQuestionnaireMoca',
  QuickNoteSectionDiagnosis = 'QuicknoteSectionDiagnosis',
  QuickNoteSectionHospitalInitial = 'QuicknoteSectionHospitalInitial',
  QuickNoteSectionHospitalOrders = 'QuicknoteSectionHospitalOrders',
  QuickNoteSectionFamilyPsychHx = 'QuicknoteSectionFamilyPsychHx',
  QuickNoteSectionPastPsychHx = 'QuicknoteSectionPastPsychHx',
  QuickNoteSectionTherapy = 'QuicknoteSectionTherapy',
  QuickNoteSectionPastMedicalHx = 'QuicknoteSectionPastMedicalHx',
  QuickNoteSectionSocialHx = 'QuicknoteSectionSocialHx',
  QuickNoteSectionSubstanceUseHx = 'QuicknoteSectionSubstanceUseHx',
  QuicknoteSectionPhysicalExam = 'QuicknoteSectionPhysicalExam',
  QuicknoteSectionReviewOfSystem = 'QuicknoteSectionReviewOfSystem',
  QuickNoteSectionPrimaryCode = 'QuicknoteSectionPrimaryCode',
  QuicknoteSectionProcedureEtcTab = 'QuicknoteSectionProcedureEtcTab',
  ProcedureTMS = 'ProcedureTMS',
  ProcedureECT = 'ProcedureECT',
  QuicknoteSectionProcedureSpravatoTab = 'QuicknoteSectionProcedureSpravatoTab',
  QuicknoteSectionProcedureSpravato = 'QuicknoteSectionProcedureSpravato',
  QuicknoteSectionHPI = 'QuicknoteSectionHPI',
  Addon = 'QuicknoteSectionAddOn',
  Vitals = 'QuicknoteSectionVital',
  QuicknoteSectionMse = 'QuicknoteSectionMse',
  FollowUps = 'FollowUps',
  QuicknoteSectionPsychiatryAssessmentPlan = 'QuicknoteSectionPsychiatryAssessmentPlan',
  QuicknoteSectionTherapyAssessmentPlan = 'QuicknoteSectionTherapyAssessmentPlan',
  QuicknoteSectionFamilyInternalMedicineAssessmentPlan = 'QuicknoteSectionFamilyInternalMedicineAssessmentPlan',
  QuicknoteSectionPatientAllergies = 'QuicknoteSectionPatientAllergies',
  QuicknoteSectionAssessmentPlan = 'QuicknoteSectionAssessmentPlan',
  QuicknoteSectionQuestionnaires = 'QuicknoteSectionQuestionnaires',
  QuicknoteSectionReferrals = 'QuicknoteSectionReferrals',
  QuicknoteSectionCodes = 'QuicknoteSectionCodes',
  QuicknoteSectionMedications = 'QuicknoteSectionMedications',
  QuicknoteSectionHospitalDischarge = 'QuicknoteSectionHospitalDischarge',
  QuicknoteSectionAdmittingDiagnosis = 'QuicknoteSectionAdmittingDiagnosis',
  QuicknoteSectionWorkingDischargeDiagnosis = 'QuicknoteSectionWorkingDischargeDiagnosis',
  QuicknoteSectionTcm = 'QuicknoteSectionTcm',
  QuicknoteSectionCreateNote = 'CreateNote',
}

const questionnairesAddToNotesSection = [
  QuickNoteSectionName.QuestionnaireActualNoteView,
  `${QuickNoteSectionName.AddToNoteQuestionnaire}-${QuickNoteSectionName.QuickNoteSectionPhq9}`,
  `${QuickNoteSectionName.AddToNoteQuestionnaire}-${QuickNoteSectionName.QuickNoteSectionGad7}`,
  `${QuickNoteSectionName.AddToNoteQuestionnaire}-${QuickNoteSectionName.QuickNoteSectionSnapIV}`,
  `${QuickNoteSectionName.AddToNoteQuestionnaire}-${QuickNoteSectionName.QuickNoteSectionDast10}`,
  `${QuickNoteSectionName.AddToNoteQuestionnaire}-${QuickNoteSectionName.QuickNoteSectionAudit}`,
  `${QuickNoteSectionName.AddToNoteQuestionnaire}-${QuickNoteSectionName.QuickNoteSectionHamD}`,
  `${QuickNoteSectionName.AddToNoteQuestionnaire}-${QuickNoteSectionName.QuickNoteSectionYbcos}`,
  `${QuickNoteSectionName.AddToNoteQuestionnaire}-${QuickNoteSectionName.QuickNoteSectionMoca}`,
  `${QuickNoteSectionName.AddToNoteQuestionnaire}-${QuickNoteSectionName.QuickNoteSectionAims}`,
  `${QuickNoteSectionName.AddToNoteQuestionnaire}-${QuickNoteSectionName.QuickNoteSectionPcl5}`,
]

export { QuickNoteSectionName, questionnairesAddToNotesSection }
