const ROUNDING_FILTERS = [
  'Provider Type',
  'Unit',
  'Room',
  'Group',
  'Primary Insurance',
  'Secondary Insurance',
  'Visit Type',
  'Visit Sequence',
  'Visit Medium',
  'Visit Status',
  'Ins Verification',
  'Diagnosis',
  'CPT Code',
  'DOA',
  'LOS',
  'LCD',
  'Legal',
  'Co-Pay',
  'Co-Ins',
  'Balance',
  'Note Signed',
]

const LIIST_VIEW_FILTERS = [
  'Location',
  'Service',
  'Unit',
  'Room',
  'Group',
  'Provider Type',
  'Provider',
  'Visit Type',
  'Visit Sequence',
  'Visit Medium',
  'Visit Status',
  'Ins Verification',
  'Primary Insurance',
  'Secondary Insurance',
  'Co-Pay',
  'Co-Ins',
  'Balance',
  'DOA',
  'LOS',
  'LCD',
  'Authorization Number',
  'Legal',
  'Note Signed',
]

const ROUNDING_FILTERS_KEY = 'rounding-filters'

enum SchedulerFilters {
  AuthorizationNumber = 'Authorization Number',
  Balance = 'Balance',
  CoInsurance = 'Co-Ins',
  CoPayment = 'Co-Pay',
  DOA = 'DOA',
  Group = 'Group',
  InsVerification = 'Ins Verification',
  LCD = 'LCD',
  Legal = 'Legal',
  LOS = 'LOS',
  Location = 'Location',
  NoteSigned = 'Note Signed',
  PrimaryInsurance = 'Primary Insurance',
  Provider = 'Provider',
  ProviderType = 'Provider Type',
  Room = 'Room',
  SecondaryInsurance = 'Secondary Insurance',
  Unit = 'Unit',
  VisitMedium = 'Visit Medium',
  VisitSequence = 'Visit Sequence',
  VisitStatus = 'Visit Status',
  VisitType = 'Visit Type',
  CptCode = 'CPT Code',
  Diagnosis = 'Diagnosis',
}

export {
  ROUNDING_FILTERS,
  ROUNDING_FILTERS_KEY,
  LIIST_VIEW_FILTERS,
  SchedulerFilters,
}
