name: Which Project(s)

on:
    workflow_call:
        outputs:
            platform:
                description: "Is platform build"
                value: ${{ jobs.paths-filter.outputs.platform }}

            clinical:
                description: "Is clinical build"
                value: ${{ jobs.paths-filter.outputs.clinical }}

            patient:
                description: "Is patient build"
                value: ${{ jobs.paths-filter.outputs.patient }}

            revcycle:
                description: "Is revcycle build"
                value: ${{ jobs.paths-filter.outputs.revcycle }}
    
jobs:
    paths-filter:
        runs-on: ubuntu-latest
        outputs:
            platform: ${{ steps.filter.output.platform}}
            clinical: ${{ steps.filter.output.clinical}}
            patient: ${{ steps.filter.output.patient}}
            revcycle: ${{ steps.filter.output.revcycle}}

        steps:
            -uses: actions/checkout@v2
            -uses: dorny/paths-filter@v2

        id: filter
            with:
                filters: |
                    platform:
                        - 'apps/platform/**'
                        - 'apps/api/**'
                    clinical:
                        - 'apps/clinical/**'
                    patient:
                        - 'apps/patient/**'
                    revcycle:
                        - 'apps/revcycle/**'
