import { PhysicalExamWidgetSchemaType } from './physical-exam-widget-schema'

export const createEmptyFormValues = (): PhysicalExamWidgetSchemaType => ({
  general: [],
  skin: [],
  heent: [],
  neck: [],
  lymphNodes: [],
  chest: [],
  cardiovascularCvs: [],
  lungs: [],
  gastrointestinalGi: [],
  adhdHyperactive: [],
  gynecologicalGyn: [],
  genitourinaryGu: [],
  centralNervousSystemCns: [],
  musculoskeletal: [],
  nutrition: [],
  psychiatric: [],
  cranialNervesExam: [],
  cneOtherDetails: '',
  gnOtherDetails: '',
  sknOtherDetails: '',
  hntOtherDetails: '',
  nkOtherDetails: '',
  lnOtherDetails: '',
  chsOtherDetails: '',
  cvsOtherDetails: '',
  lngOtherDetails: '',
  giOtherDetails: '',
  gynOtherDetails: '',
  guOtherDetails: '',
  cnsOtherDetails: '',
  msuOtherDetails: '',
  mutOtherDetails: '',
  psyOtherDetails: '',
  nutOtherDetails: '',
  widgetContainerCheckboxField: '',
})
