const CLAIM_LIST_TABLE_PAGE_SIZE = 20
const SUBMISSION_LIST_TABLE_PAGE_SIZE = 20
const INSURANCE_PAYMENT_LIST_TABLE_PAGE_SIZE = 20
const PATIENT_STATEMENTS_LIST_TABLE_PAGE_SIZE = 20
const PATIENT_STATEMENT_TABLE_PAGE_SIZE = 20
const RESPONSE_HISTORY_TABLE_PAGE_SIZE = 20
const PATIENT_LIST_OPTION_SIZE = 20
const INSURANCE_PAYER_LIST_OPTION_SIZE = 20

export {
  CLAIM_LIST_TABLE_PAGE_SIZE,
  SUBMISSION_LIST_TABLE_PAGE_SIZE,
  INSURANCE_PAYMENT_LIST_TABLE_PAGE_SIZE,
  PATIENT_STATEMENTS_LIST_TABLE_PAGE_SIZE,
  PATIENT_STATEMENT_TABLE_PAGE_SIZE,
  RESPONSE_HISTORY_TABLE_PAGE_SIZE,
  PATIENT_LIST_OPTION_SIZE,
  INSURANCE_PAYER_LIST_OPTION_SIZE,
}
