export { PatientInfo } from './patient-info/patient-info'
export { AddInsurance } from './add-insurance/add-insurance'
export { Payment } from './payment/payment'
export { AllergiesAndMedications } from './allergies-and-medications/allergies-and-medications'
export { Pharmacy } from './pharmacy/pharmacy'
export { PresentingSymptoms } from './presenting-symptoms/presenting-symptoms'
export { Histories } from './histories/histories'
export { ReviewOfSystems } from './review-of-systems/review-of-systems'
export * from './questionnaire'
