import { z } from 'zod'
import { VADPRS_QUESTION_IDS, VADPRS_PERFORMANCE_QUESTION_IDS, VADPRS_CHILD_EVALUATION } from './constants'

type VadprsSchemaType = {
  [key: string]: string
}

const VadprsSchema = z.object({
  [VADPRS_CHILD_EVALUATION]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q1]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q2]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q3]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q4]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q5]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q6]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q7]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q8]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q9]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q10]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q11]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q12]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q13]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q14]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q15]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q16]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q17]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q18]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q19]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q20]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q21]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q22]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q23]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q24]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q25]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q26]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q27]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q28]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q29]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q30]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q31]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q32]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q33]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q34]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q35]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q36]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q37]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q38]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q39]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q40]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q41]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q42]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q43]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q44]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q45]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q46]: z.string().nullable(),
  [VADPRS_QUESTION_IDS.Q47]: z.string().nullable(),
  [VADPRS_PERFORMANCE_QUESTION_IDS.Q48]: z.string().nullable(),
  [VADPRS_PERFORMANCE_QUESTION_IDS.Q49]: z.string().nullable(),
  [VADPRS_PERFORMANCE_QUESTION_IDS.Q50]: z.string().nullable(),
  [VADPRS_PERFORMANCE_QUESTION_IDS.Q51]: z.string().nullable(),
  [VADPRS_PERFORMANCE_QUESTION_IDS.Q52]: z.string().nullable(),
  [VADPRS_PERFORMANCE_QUESTION_IDS.Q53]: z.string().nullable(),
  [VADPRS_PERFORMANCE_QUESTION_IDS.Q54]: z.string().nullable(),
  [VADPRS_PERFORMANCE_QUESTION_IDS.Q55]: z.string().nullable(),
})

export { VadprsSchema, type VadprsSchemaType }
