const ORGANIZATIONS_STAFF_LIST_TABLE_PAGE_SIZE = 20

enum FEATURE_TYPES {
  ORGANIZATION = 'organizations',
  PRACTICE = 'practices',
}

export { ORGANIZATIONS_STAFF_LIST_TABLE_PAGE_SIZE, FEATURE_TYPES }
