const PATIENT_REFERRALS_TABLE_PAGE_SIZE = 20
const DEFAULT_REFERRAL_SERVICE_STATUS = 'Routine'
const EMERGENCY_REFERRAL_SERVICE_STATUS = 'Emergency'
const DISABLE_CODESET_ATTRIBUTE = 'IsUserSelectable'

export {
  PATIENT_REFERRALS_TABLE_PAGE_SIZE,
  DEFAULT_REFERRAL_SERVICE_STATUS,
  EMERGENCY_REFERRAL_SERVICE_STATUS,
  DISABLE_CODESET_ATTRIBUTE,
}
