const REPORT_LIST_TABLE_PAGE_SIZE = 10
const REPORT_SCHEDULE_LIST_TABLE_PAGE_SIZE = 10

export enum RECORD_STATUS {
  ACTIVE = 'Active',
  INACTIVE = 'Inactive',
}

export { REPORT_LIST_TABLE_PAGE_SIZE, REPORT_SCHEDULE_LIST_TABLE_PAGE_SIZE }
