const LABELS = ['Questions', 'True', 'False']

const DEFAULT_OPTIONS = [
  {
    label: 'True',
    value: '1',
  },
  {
    label: 'False',
    value: '0',
  },
]

const QUESTIONS_TEXTS = [
  'My mother was a high strung and excitable person.',
  'I was a member of one or more high school (varsity or similar) sports teams.',
  'I have been arrested, or have had criminal charges against me, for some offense regardless of the final outcome.',
  'I have been convicted, received probation, paid a fine, or had another similar outcome (other than acquittal or outright dismissal) with respect to at least one arrest referred to above.',
  'I felt my mother was too overprotective towards me.',
  'Our family lived in three or more cities or towns before I was sixteen.',
  'I served in the Marine Corps or Special Forces.',
  'There was a lot of friction between my father and myself as I was growing up.',
  'I was a member of the Boy (or Girl) Scouts, or a similar organization, for at least two years.',
  "I think most people will get away with as much as they can, for as long as they can, unless they're caught.",
  'I am the oldest in a family with more than one child.',
  'My father was really tough on me (or on all the children) and my mother tried to make up for it by being protective of me (answer "True" only if both are true).',
  'I have to admit, there have been times in my life when I have lied.',
  'I felt frustrated and unhappy a lot when I was younger.',
  'I really liked my father and got along well with him when I was a teenager.',
  'On average, I drink alcoholic beverages less than 10 times a year, or I do not drink (alcoholic beverages) at all.',
  'Within the last three years, I have had problems with my credit rating or had problems because of too much debt.',
  'I will sleep more than eight hours a day any time I can.',
  "I tend to put off doing things that I don't like.",
  "I have never taken anything that didn't belong to me, regardless of its value.",
  'When I was young, there was a lot of fighting (not just minor squabbling) among members of my family.',
  'I think the most important thing that makes people obey the law, is fear of getting caught.',
  'Like it or not, minority group members are just more likely to commit violent crimes than most other people are.',
  'It seems to me that luck is the most important single factor in getting ahead in life.',
  'I smoked marijuana at least three times when I was younger.',
  'Given a chance, most people would take something that did not belong to them, if they could get away with it.',
  'I have lost one or more friendships or relationships in the past because of my drinking or use of drugs.',
  "You can't let yourself be soft in dealing with the public because they will take advantage.",
  'Some of my friends or family members think I drink too much or, if I stopped drinking within the last three years, that I used to drink too much.',
  "You can't really get ahead in this country unless you are also willing to be a little dishonest.",
  'I served in the military, and I received a discharge that was not the standard honorable type (for example, general under honorable conditions, medical, at convenience of the government, etc.).',
  'I believe that if you do not punish children when they misbehave, you will generally spoil the child (i.e. "spare the rod and spoil the child").',
  "Certain minority groups seem to want a lot, but they don't seem to be willing to earn it, like others before them did.",
  'I have made one or more bad decisions because of drinking.',
  "Once in a while when nobody's around, I've done things that I would have been embarrassed to have anyone see me doing.",
  'I am a gun collector, and I own four or more firearms.',
  'I am told I am opinionated.',
  'I have certain mental abilities or powers that I do not talk about to others.',
  'I am usually quite good at understanding the way other people feel.',
  'There are certain jobs, including police, firefighting, or corrections work, for which the great majority of women are just not suited.',
  'I have been fired from at least one job in my life since the age of eighteen (do not count simple layoffs due to lack of work).',
  'I was in the military, and I had one or more disciplinary problems while there.',
  'I have been asked to resign from some job or else been fired.',
  'There have been times in my life when I felt upset for no apparent reason or seriously felt as if I were losing control of myself.',
  'When I was in high school, I was considered to be a leader among my peers.',
  'I have had at least three different full-time jobs during the last two years (do not count part-time or contract labor jobs, such as assigned by a construction trade union).',
  'I grew up on a farm or in a very rural area.',
  'As I was growing up, I had many chores to do around my home.',
  'To tell the truth, when I see a racially mixed couple it makes me feel pretty disgusted.',
  'When I have to, I can be a pretty good liar.',
  'I used to be a pretty wild kid, but I have calmed down a lot.',
  'I have been married and have divorced at least once.',
  'I am currently married, and we have one or more children living at home with us.',
  'When I was young, I shoplifted a few times.',
  'I have been charged with at least one DWI, DUI (driving under the influence), or other drinking and operating a motorized vehicle offense.',
  'I had an in-school or out of school suspension in high school for cutting classes, fighting, or for some other reason.',
  "My driver's license has been suspended or revoked at least once.",
  'The real reason that the majority of so-called "minorities" can\'t get ahead is that they have no self-discipline.',
  'I have held my present job for two years or more.',
  'I have never been fired, asked to resign, or had any serious problems with any of my bosses (answer true if all are true).',
  'Sometimes I have a strange feeling, as if I am outside of my body, or as if my body does not belong to me.',
  'I generally earned above average grades when I was in high school, and I was awarded a regular high school diploma upon graduation.',
  'I have completed one or more years of a college education.',
  'I often think about myself dying, and it scares me.',
  "I seem to care about other peoples' feelings and problems more than most people do.",
  'I am now, or I have been a public safety employee, and I have had one or more complaints made against me for which I have received a written warning or reprimand or received some form of punishment or discipline.',
  'I consider myself to be a fairly spiritual person, whether or not I attend any kind of religious services or belong to any religious group.',
  'I must admit that I used to be pretty hot tempered when I was younger.',
  'I will not just go along with orders because a boss says "do it." I need to know the reasons why.',
  'I have seriously thought about committing suicide at some point in my life.',
  'I have lived five, or more, of the past seven years at the same address.',
  'I have received less than five traffic tickets in my life for any offense (seatbelt, cell phone, speeding, etc.).',
  "One or more members of my close family are in public safety work: police officer, firefighter, sheriff's department, etc.",
  'It seems to me that the old saying that "good guys finish last" is basically true.',
  'I have never told anyone about something after I have been asked to keep it a secret.',
  'I have had public safety or public service experience as a volunteer (e.g. volunteer firefighter, auxiliary police, first aid squad).',
  'I was the captain of a sports team or president of a school club or student group in high school.',
  "We spend too much money keeping the 'scum of the earth' alive in prisons. If someone is convicted of a violent crime more than once, they should get the death penalty.",
  'Having a woman on a squad is really more trouble than a help in an emergency situation.',
  'Whether or not I was at fault, I have had at least two motor vehicle accidents in the last five years (do not count any accidents in which you were a pedestrian or passenger).',
  'Regardless of whether I was found guilty, I have been arrested for or criminally charged with a physical assault at least once. (If you are or were a police or sheriff\'s officer and these were countercharges which were all dismissed, answer "False").',
  'Both of my parents were over thirty-five years old when I was born.',
  'I have not had a physical fight (outside of line of duty) in over five years.',
  'I have two or more tattoos.',
  'I believe people have very little control over the really important things that happen to them in their lives.',
  'I have some fears that I do not even admit to my friends.',
  'Whether or not I agree, some of my friends or family members consider me to be a moody person.',
  'There is a lot of stress in my life lately.',
  'Even when I have slept a good eight hours, I find it hard to get up most mornings.',
  "People who have a lot of money usually think that they are better than everyone else and that they don't have to follow the same rules.",
  'I have to admit, that I have a tendency to get upset over silly things that others generally seem to ignore.',
  'When I was young, I was small (or fat, or somehow different from the others) and I was picked on more than most other kids I knew.',
  'I find it hard to express myself in words.',
  'You have to punish children to teach them right from wrong.',
  'There is nothing that I can think of that scares me.',
  'After a while, most people in public life start to get a little corrupted by the temptations around them.',
  'If somebody cuts in front of me in a line, I will generally say something to them about it.',
  'My family is more important to me than my friends.',
  'It seems to me that people with the most education usually have the least common sense.',
  'I will not stand for anyone "putting me down" or "pushing me around" verbally, regardless of who it is, or why they are doing it.',
  'I held enlisted rank in the military, and I was honorably discharged at a rank of E-4 or higher.',
  'Someone in my immediate family (other than myself) has been in serious trouble with the law.',
  'My parents were divorced or separated before I was eighteen (do not include separation by death of a parent, if your parents were together up to the time one died).',
  "My temper used to be pretty 'hot', and got me into trouble sometime in my life, since grade school.",
  'Once in a while, I have driven five or ten miles over the speed limit.',
  'I drink something with alcohol in it (wine, beer, etc.) three or more times in a week, on average.',
  "Loud mouthed 'wise guys' tend to be irritating to me, whether or not I show it at the time.",
  "Deep down, I believe that if people want to use drugs and kill themselves, it's their own business and not ours.",
  'There are certain things that my friends may not like about me, even though they remain my friends.',
  'My mother worried too much about me and kept me from doing many normal things other kids my age did.',
  'I have a hard time falling asleep.',
  'I have gotten into at least one fight in my life while I was drinking, whether or not I started it.',
  'Most people are basically a little dishonest.',
  'I have had psychological or psychiatric treatment for a personal problem at some time in my life after the age of twelve.',
  'Whether or not I show it, I can sometimes get so irritable, that I feel like blowing up at the next person who bothers me.',
  'I tend to feel bad if I make anyone wait for me when I am late.',
  'Although they may be in charge, bosses are not always smarter people than their employees.',
  'All in all, I like myself just the way I am.',
  'I believe my own choices are basically responsible for most of the important things that have happened to me in my own life.',
  "I usually have my own ideas on things, and I don't tend to change them easily. Once my mind is made up, I usually stick to my opinions.",
  'I am optimistic about what the future holds for me.',
  'I like to get an adrenaline rush and do things that are exciting and may even be a bit dangerous.',
  'I never act or speak before I have thought it through.',
  'I must admit, that I secretly tend to feel good when I see bosses make fools of themselves.',
  'I have had some bad periods of depression in my life.',
  'It never bothers me to be told what to do by someone who is in charge, regardless of what it is.',
  'My father worked a lot and did not have much time for the kids as I was growing up.',
  'I tend to get frustrated when I am sitting in a traffic jam.',
  "I do not back down if I think somebody is trying to push me into an argument. I don't walk away from a fight.",
  'I have bought a life insurance policy on myself to protect my family in case of my death.',
  'I am female and have experienced harassment on one or more jobs because of it.',
  'I and some friend(s) will go to a bar on the average of at least once a week.',
  'I had a job or some other type of paid work experience by the age of 15, or before.',
  'I am a female, and I have had one or more physical fights (not in the line of duty) since I have been eighteen.',
  'I tend to think a lot about my own behavior and image and how I "come across" to other people.',
  'After work I like to unwind with a couple of drinks.',
  'I grew up (to age eighteen) with both of my natural parents at home and together.',
  'I have completed and been awarded a two- or four-year college degree.',
  'At times, in the middle of a conversation, my mind can wander to something else entirely.',
  'Life is pretty much a continual struggle to keep others from holding you back while you are trying to get ahead.',
  'I frequently find that I end up spending my weekends alone.',
  'If you are a citizen, you should not be allowed to refuse to salute your flag or to stand for the national anthem.',
  'Even though women talk about wanting equality, the truth is they generally want to be taken care of.',
  'When someone has a lot to say at a meeting, I sometimes secretly wish they would just "shut up."',
  'I tend to be a "work-a-holic" and sometimes don\'t know when to quit.',
  'I was late for my job three or more times in the last year.',
  "It's a boss' job to get the most out of you. It's your job to keep him (or her) from getting away with it.",
  'I think it is important to dress well for any occasion when you are meeting new people.',
  'When I was in high school, I found that the teachers were often stupid, or unfair, or both.',
  'In addition to marijuana, I tried some other drugs a few times when I was younger.',
  'There are very few people I think can be trusted.',
  'I would rather take pictures of animals than hunt them.',
  'I have a really good sense of humor.',
  'All in all, life has been pretty good for me, so far.',
  'I tend to worry about small things more than I should while most people just tend to ignore them.',
  'I can swim.',
  'I have never been charged with any criminal offense after the age of seventeen (do not count normal traffic offenses).',
  "The future doesn't look too bright to me right now.",
  "Life is a pretty lonely thing. You can't really expect to have much help from others when things get rough.",
  'In my personal experience, I have found that black people are usually less intelligent than most whites.',
  'It bothers me when the people I live or work with do not keep their own things in an orderly manner.',
  "You've got to watch out for yourself in this world, because if you don't, nobody else will look out for your best interests.",
  'I have been out of work because of illness more than three separate periods of time in the last year.',
  'I have sometimes heard voices speaking to me when there was no one there or had visions of things which others could not see.',
  'I believe that most people will cheat on their income taxes, if they believe they can get away with it.',
  'I have quit at least three different jobs in the past two years (do not count part times jobs).',
  'It may take a lot to get me angry, but when I finally blow up, I really let go.',
  'When I was a teenager, I was pretty outgoing, and I had a lot of friends.',
  "In general, I believe you can't trust most women.",
  'I feel pretty stressed on my present job.',
  'I tend to wake up a few times each night.',
  'I have seriously thought about or actually attempted suicide at least once in my life.',
  'I generally don\'t "open up" to anyone about the way I really feel.',
  'I never let anything get me angry.',
  'I find I can often laugh at myself.',
  'I have had periods when I was afraid for no reason, or I felt like I could not go into an elevator, drive through a tunnel or over a bridge, or do other things that are usually no problem.',
  'I have previously taken one or more psychological tests for a job and failed at least once.',
  "It can't be denied that when minorities take over a residential neighborhood, they usually tend to ruin it.",
  'I have to admit that I tend to be more easily upset and more of a worrier than most of my friends.',
  'I am now, or have been, a public safety employee and I have never had any disciplinary problems, (sustained complaints, written reprimands, warnings, etc.) during my public career.',
  'I have lost at least one friendship or relationship with someone I was close to, because of my own drug or alcohol use at the time.',
  'I have to admit that I have a tendency to get upset over silly little things.',
  'At this time in life, I feel that my friends are more important to me than my family.',
  "I honestly believe that many minority supervisors get their jobs just because they are minorities. I often find they can't do the job as well as someone else who was passed over.",
  'I will not fly in airplanes. If I have to travel a distance, I will find some other way of doing it.',
  'Like it or not, if I had a woman in my squad, I would feel obligated to look out for her safety more than I would with a fellow male officer in a dangerous situation.',
  'My temper has gotten me into trouble since the age of eighteen.',
  'I have taken prescription medicine for some nervous or emotional problem.',
  'I like to keep myself busy and usually create one or more projects of my own to occupy my time.',
  'I have been hospitalized for emotional or psychological problems at some time in my life.',
  'I have been named in a restraining order or have obtained one against someone else.',
  'I have some real enemies.',
  'I do not let anyone push me around, even verbally, and get away with it. I feel you have to respond immediately, regardless of who it is doing it to you, or why.',
  'I have had instances when I felt as if I was having a heart attack or that my nerves were out of control.',
  'Whether or not I have been convicted, I have been given a summons for, or charged with, the possession of marijuana, or some other illegal substance.',
  'Certain minority groups have gotten too much influence in this country. Soon, the natural born citizens will be the second-class citizens.',
  'I have had at least one period of four or more months in my adult life (past the age of eighteen) when I did not work or go to school or have a serious responsibility at home.',
  'If you have to confront a violent or dangerous situation, having a woman partner will likely make it more difficult.',
  'I often did not get along with my father when I was growing up.',
  'To tell the truth, I believe that we would all be better off if the races stuck to their own kind, and did not mix in schools, in neighborhoods, or by dating or marrying.',
  'I believe that God ordained men to be the natural leaders and women to follow.',
  'I keep my personal things neat and orderly. I usually know where anything of mine is at any time.',
  'I tend to be pretty serious, and, as a rule, I do not joke around much with my co-workers.',
  'If you had an equally qualified man and woman, I believe it makes more sense to hire the man, especially for a job like law enforcement or public safety.',
  'Sometimes I feel shy and self-conscious in social situations for no apparent reason.',
  'I had a job, or some kind of real responsibility, as far back as I can remember.',
  'Most women who want to join largely male organizations are either looking for a man or want to be one.',
  'Among the hardest problems that I face is making important decisions.',
  "I must admit that I tend to procrastinate, especially when I have a job to do that I don't like.",
  'In high school, I was often a leader in sports, clubs, or other activities, or in school government.',
  'My personal relationships have been somewhat of a "mess" lately.',
  'I grew up speaking a foreign language as well as English.',
  'I grew up in a poor, inner city neighborhood (at least to the age of thirteen).',
  'I believe that being able to "do my own thing" is very important to my happiness.',
  'In this world, the rule is "get the other guy before he gets you."',
  'I think I am basically the same as I was five years ago, so far as my personality is concerned.',
  'On several occasions, I have gambled more money than I should have.',
  'If I am at work and I have no unfinished assignment, I will generally look for something useful to do, rather than just sit around.',
  "Sometimes, even when nothing is really going wrong, I have felt angry, or irritable, or very sad, even if I don't show it.",
  'I have taken something of at least five dollars in value from some past job or other place, without authorization.',
  'I have been in a drug or alcohol rehabilitation program at least once in my life.',
  'I am now, or I have been, a member of Alcoholics Anonymous or a similar twelve step group.',
  'It is correct to say, I have never been treated by a professional for personal or emotional problems.',
  'I have had some serious health problems in the last five years.',
  'It is correct to say that I have never gone into personal bankruptcy.',
  'There have been times in my life when I was afraid for no reason or could not get myself to do certain things (like ride an elevator, drive on a big highway or go in a store).',
  'I have been given a summons for, or been charged with, an alcohol related offense (urinating in public after drinking, underage possession of alcohol, public intoxication, open container, etc.).',
  'I am currently receiving, or have previously received, medication for a psychiatric or emotional condition.',
  'I have started a business of my own one or more times in my life.',
  'The truth is, having women in certain organizations which have always been male, such as the police, fire, or corrections departments, tends to reduce effectiveness and respect for the organization.',
  'I have been deliberately assaulted by a boyfriend (or a girlfriend) at some time in my life.',
  'I have had someone try to get a restraining order against me at some time in my life, or I have tried to get one against someone else.',
  "I often find I can't resist a real bargain.",
  'I have been charged at some time, with illegal possession of a weapon (regardless of outcome).',
  'To tell the truth, if I had to choose between making good money at a boring job and making less doing more interesting work, I would probably go for the better money.',
  'Women tend to be ruled by their emotions, which can be dangerous or a major problem in public safety work.',
  'I have been put in jail due to some arrest, for a period of twenty-four hours or more.',
  'I see life as full of opportunities to do anything legitimate that I choose to do.',
  "I really can't stand some of the people I work with.",
  'When I was younger, I had personality characteristics that I think would really annoy me if I met someone like that today.',
]

const QUESTIONS = QUESTIONS_TEXTS.map((item, index) => ({
  id: `Q${index + 1}`,
  question: item,
  value: 0,
  options: DEFAULT_OPTIONS,
}))

export { LABELS, QUESTIONS }
