const INT_REFERRALS_TABLE_PAGE_SIZE = 20
const INT_REFERRALS_FILTERS_KEY = 'int-referrals-filters'
const DISABLE_CODESET_ATTRIBUTE = 'IsUserSelectable'

export {
  INT_REFERRALS_TABLE_PAGE_SIZE,
  INT_REFERRALS_FILTERS_KEY,
  DISABLE_CODESET_ATTRIBUTE,
}
