const USER_WIDGET = 'user'
const PATIENT_WIDGET = 'patient'
const PATIENT_REFERRALS_LIST_WIDGET = 'patient-referrals'
const ALL_REFERRALS_LIST_WIDGET = 'all-referrals'
const CREATE_REFERRAL_WIDGET = 'create-referral'
const EDIT_REFERRAL_WIDGET = 'edit-referral'
const REFERRAL_DETAILS_WIDGET = 'referral-details'
const SCHEDULE_APPOINTMENT_DIALOG = 'schedule-appointment-dialog'
const SCHEDULE_APPOINTMENT_LIST = 'schedule-appointment-list'
const OTP_DIALOG = 'otp-dialog'
const PREFERRED_PARTNERS_LIST_WIDGET = 'preferred-partners'
const CREATE_PREFERRED_PARTNER = 'create-preferred-partner'
const ADD_TEMPLATE_WIDGET = 'add-template'
const EDIT_TEMPLATE_WIDGET = 'edit-template'
const REPORTS_WIDGET = 'reports-widget'

export {
  USER_WIDGET,
  PATIENT_WIDGET,
  PATIENT_REFERRALS_LIST_WIDGET,
  ALL_REFERRALS_LIST_WIDGET,
  CREATE_REFERRAL_WIDGET,
  EDIT_REFERRAL_WIDGET,
  REFERRAL_DETAILS_WIDGET,
  SCHEDULE_APPOINTMENT_DIALOG,
  SCHEDULE_APPOINTMENT_LIST,
  OTP_DIALOG,
  PREFERRED_PARTNERS_LIST_WIDGET,
  CREATE_PREFERRED_PARTNER,
  ADD_TEMPLATE_WIDGET,
  EDIT_TEMPLATE_WIDGET,
  REPORTS_WIDGET,
}
