const USER_WIDGET = 'user'
const PATIENT_WIDGET = 'patient'
const PATIENT_REFERRALS_LIST_WIDGET = 'patient-referrals'
const LAB_ORDER = 'laborder'
const ADD_LAB_ORDER_RESULT = 'add-laborder-result'
const ALL_REFERRALS_LIST_WIDGET = 'all-referrals'
const CREATE_REFERRAL_WIDGET = 'create-referral'
const EDIT_REFERRAL_WIDGET = 'edit-referral'
const REFERRAL_DETAILS_WIDGET = 'referral-details'
const SCHEDULE_APPOINTMENT_DIALOG = 'schedule-appointment-dialog'
const SCHEDULE_APPOINTMENT_LIST = 'schedule-appointment-list'
const OTP_DIALOG = 'otp-dialog'
const PREFERRED_PARTNERS_LIST_WIDGET = 'preferred-partners'
const ASSESSMENT_AND_TREATMENT_PLAN_LIST_WIDGET =
  'assessment-and-treatment-plans'
const ASSESSMENT_AND_TREATMENT_PLAN_DETAIL_WIDGET =
  'assessment-and-treatment-plan-detail'
const CREATE_PREFERRED_PARTNER = 'create-preferred-partner'
const ADD_TEMPLATE_WIDGET = 'add-template'
const EDIT_TEMPLATE_WIDGET = 'edit-template'
const REPORTS_WIDGET = 'reports-widget'
const CREATE_CLEARING_HOUSE_RECEIVER = 'create-clearing-house-receiver'
const PATIENT_INFORMATION_WIDGET = 'patient-info-widget'
const LINK_ACCOUNT_WIDGET = 'link-account-widget'
const ADD_RELATIONSHIP_WIDGET = 'add-relationship-widget'
const PATIENT_RELATIONSHIPS_WIDGET = 'patient-relationships-widget'
const PATIENT_PREFERRED_PARTNERS_WIDGET = 'patient-preferred-partners-widget'
const ENLARGE_IMAGE_WIDGET = 'enlarge-image'
const CAPTURE_IMAGE_WIDGET = 'capture-image'
const HEALTH_CONCERN_LIST_WIDGET = 'health-concern'
const PROBLEMS_LIST_WIDGET = 'problems'
const CARE_PLANS_WIDGET = 'care=plans'
const ACTIVE_CODESET_LIST_WIDGET = 'active-codesets'
const ASSIGNING_AUTHORITIES_WIDGET = 'assigning-authorities'
const PATIENT_HISTORY_WIDGET = 'patient-history'
const CLINIC_WIDGET = 'clinic-widget'
const MANAGEMENT_LOCATIONS_WIDGET = 'management-locations'
const MANAGEMENT_USERS_WIDGET = 'management-users-widget'
const PROCEDURES_LIST_WIDGET = 'procedures'
const ADD_MANAGEMENT_SERVICE_WIDGET = 'add-management-service'
const EDIT_MANAGEMENT_SERVICE = 'edit-managemet-service'
const EDIT_MANAGEMENT_LOCATION_WIDGET = 'edit-management-location'
const MANAGEMENT_SERVICES_LIST_WIDGET = 'management-services-list'
const ADD_MANAGEMENT_LOCATIONS_WIDGET = 'add-management-locations'
const NOTES_WIDGET = 'notes-widget'
const MANAGEMENT_LOCATION_TABS_WIDGET = 'management-location-tabs'
const ADD_EXT_REFERRALS_FORM = 'add-ext-referrals-form'
export {
  USER_WIDGET,
  PATIENT_WIDGET,
  LAB_ORDER,
  ADD_LAB_ORDER_RESULT,
  PATIENT_REFERRALS_LIST_WIDGET,
  ALL_REFERRALS_LIST_WIDGET,
  CREATE_REFERRAL_WIDGET,
  EDIT_REFERRAL_WIDGET,
  REFERRAL_DETAILS_WIDGET,
  SCHEDULE_APPOINTMENT_DIALOG,
  SCHEDULE_APPOINTMENT_LIST,
  OTP_DIALOG,
  PREFERRED_PARTNERS_LIST_WIDGET,
  CREATE_PREFERRED_PARTNER,
  ADD_TEMPLATE_WIDGET,
  EDIT_TEMPLATE_WIDGET,
  REPORTS_WIDGET,
  CREATE_CLEARING_HOUSE_RECEIVER,
  PATIENT_INFORMATION_WIDGET,
  LINK_ACCOUNT_WIDGET,
  ADD_RELATIONSHIP_WIDGET,
  PATIENT_RELATIONSHIPS_WIDGET,
  PATIENT_PREFERRED_PARTNERS_WIDGET,
  ENLARGE_IMAGE_WIDGET,
  CAPTURE_IMAGE_WIDGET,
  HEALTH_CONCERN_LIST_WIDGET,
  PROBLEMS_LIST_WIDGET,
  ASSESSMENT_AND_TREATMENT_PLAN_LIST_WIDGET,
  ASSESSMENT_AND_TREATMENT_PLAN_DETAIL_WIDGET,
  CARE_PLANS_WIDGET,
  ACTIVE_CODESET_LIST_WIDGET,
  ASSIGNING_AUTHORITIES_WIDGET,
  PATIENT_HISTORY_WIDGET,
  CLINIC_WIDGET,
  MANAGEMENT_LOCATIONS_WIDGET,
  MANAGEMENT_USERS_WIDGET,
  PROCEDURES_LIST_WIDGET,
  ADD_MANAGEMENT_SERVICE_WIDGET,
  EDIT_MANAGEMENT_SERVICE,
  EDIT_MANAGEMENT_LOCATION_WIDGET,
  MANAGEMENT_SERVICES_LIST_WIDGET,
  ADD_MANAGEMENT_LOCATIONS_WIDGET,
  NOTES_WIDGET,
  MANAGEMENT_LOCATION_TABS_WIDGET,
  ADD_EXT_REFERRALS_FORM
}
