export const NEXT_OPTIONS = [
  'Outpatient Office Visit',
  'ED Visit',
  'Transitional Care Management',
  'Hospital Care | Initial',
  'Individual Psychotherapy',
  'Family/Couple Psychotherapy',
  'Group Therapy',
  'TMS Visit',
  'ECT Visit',
  'Spravato Visit',
  'Ketamine IV',
  'IV/IM Therapy',
  'TMS Consult',
  'Spravato Consult',
  'Ketamine IV Consult',
  'Surgical Clearance',
  'PCM By Physician/QHCP',
  'PCM By clinical staff',
  'Hospital Care | Subsequent',
  'Hospital Care | Discharge',
  'Hospital Care | Initial/Discharge',
  'Behavior Identification Assessment',
  'Behavior Identification Supporting Assessment',
  'Destructive Behavior Identification Supporting Assessment',
  'Adaptive Behavior Treatment',
  'Adaptive Behavior Treatment with Protocol Modification',
  'Destructive Adaptive Behavior Treatment with Protocol Modification',
  'Group Adaptive Behavior Treatment',
  'Group Adaptive Behavior Treatment with Protocol Modification',
  'Family Adaptive Behavior Treatment Guidance',
  'Multiple Family Adaptive Behavior Treatment Guidance',
].map((label) => ({ value: label, label }))
