const LABELS = [
  'Questions',
  'Never',
  'Almost never',
  'Rarely',
  'At times',
  'Sometimes',
  'About half the time',
  'Fairly often',
  'Often',
  'Very Often',
  'Almost always',
  'Always',
]

const QUESTIONS = [
  'Some people have the experience of driving/riding in a car/bus/subway and suddenly realizing that they don’t remember what has happened during all/part of the trip.',
  'Some people find that sometimes they are listening to someone talk and they suddenly realize that they did not hear part or all of what was said.',
  'Some people have the experience of finding themselves in a place and have no idea how they got there.',
  'Some people have the experience of finding themselves dressed in clothes that they don’t remember putting on.',
  'Some people have the experience of finding new things among their belongings that they do not remember buying.',
  'Some people sometimes find that they are approached by people that they do not know, who call them by another name or insist that they have met them before.',
  'Some people sometimes have the experience of feeling as though they are standing next to themselves or watching themselves do something and they actually see themselves as if they were looking at another person.',
  'Some people are told that they sometimes do not recognize friends or family members.',
  'Some people find that they have no memory for some important events in their lives, for example, a wedding or graduation.',
  'Some people have the experience of being accused of lying when they do not think that they have lied.',
  'Some people have the experience of looking in a mirror and not recognizing themselves.',
  'Some people have the experience of feeling that other people, objects, and the world around them are not real.',
  'Some people have the experience of feeling that their body does not seem to belong to them.',
  'Some people have the experience of sometimes remembering a past event so vividly that they feel as if they were reliving that event.',
  'Some people have the experience of not being sure whether things that they remember happening really did happen or whether they just dreamed them.',
  'Some people have the experience of being in a familiar place but finding it strange and unfamiliar.',
  'Some people find that when they are watching television or a movie they become so absorbed in the story that they are unaware of other events happening around them.',
  'Some people find that they become so involved in a fantasy or daydream that it feels as though it were really happening to them.',
  'Some people find that they sometimes are able to ignore pain.',
  'Some people find that they sometimes sit staring off into space, thinking of nothing, and are not aware of the passage of time.',
  'Some people sometimes find that when they are alone, they talk out loud to themselves.',
  'Some people find that in one situation they may act so differently compared with another situation that they feel almost as if they were two different people.',
  'Some people sometimes find that in certain situations they are able to do things with amazing ease and spontaneity that would usually be difficult for them. ex. sports, work, social situations.',
  'Some people sometimes find that they cannot remember whether they have done something or have just thought about doing that thing. ex. not knowing whether they have just mailed a letter or have just thought about mailing it',
  'Some people find evidence that they have done things that they do not remember doing.',
  'Some people sometimes find writings, drawings, or notes among their belongings that they must have done but cannot remember doing.',
  ' Some people sometimes find that they hear voices inside their head that tell them to do things or comment on things that they are doing.',
  'Some people sometimes feel as if they are looking at the world through a fog, so that people and objects appear far away or unclear.',
].map((question, index) => ({
  id: `Q${index + 1}`,
  question,
  value: 0,
  options: [
    { label: '0%', value: '0' },
    { label: '10%', value: '10' },
    { label: '20%', value: '20' },
    { label: '30%', value: '30' },
    { label: '40%', value: '40' },
    { label: '50%', value: '50' },
    { label: '60%', value: '60' },
    { label: '70%', value: '70' },
    { label: '80%', value: '80' },
    { label: '90%', value: '90' },
    { label: '100%', value: '100' },
  ],
}))

const SCORE_INTERPRETATION_RANGES = [
  { label: 'Normal (Norm)', color: 'white', min: 0, max: 11 },
  {
    label: 'Mild (Above avg w/n normal limits)',
    color: 'green',
    min: 12,
    max: 19,
  },
  {
    label: 'Moderate (notable dissociative experiences)',
    color: 'yellow',
    min: 20,
    max: 29,
  },
  {
    label: 'High (substantial dissociative symptoms)',
    color: 'red',
    min: 30,
    max: 44,
  },
  {
    label: 'Very High (extreme dissociative experiences)',
    color: 'dark red',
    min: 45,
    max: 100,
  },
]

export { QUESTIONS, SCORE_INTERPRETATION_RANGES, LABELS }
