const STAFF_BIO_VIDEO_MAX_SIZE = 4
const STAFF_BIO_VIDEO_SIZE_ERROR = `Video size exceeds the allowed limit of ${STAFF_BIO_VIDEO_MAX_SIZE}MB.`
export { STAFF_BIO_VIDEO_MAX_SIZE, STAFF_BIO_VIDEO_SIZE_ERROR }
