enum NoteSectionName {
  NoteSectionQuestionnaire = 'QuicknoteSectionQuestionnaire',
  NoteSectionDashboard = 'QuicknoteSectionDashboard',
  NoteSectionHPI = 'QuicknoteSectionHPI',
  NoteSectionReviewOfSystem = 'QuicknoteSectionReviewOfSystem',
  NoteSectionDast10 = 'QuicknoteSectionQuestionnaireDast10',
  NoteSectionGad7 = 'QuicknoteSectionQuestionnaireGad7',
  NoteSectionPcl5 = 'QuicknoteSectionQuestionnairePcl5',
  NoteSectionPhq9 = 'QuicknoteSectionQuestionnairePhq9',
  NoteSectionSnapIV = 'QuicknoteSectionQuestionnaireSnapIV',
  NoteSectionYbocs = 'QuicknoteSectionQuestionnaireYbocs',
  NoteSectionAudit = 'QuicknoteSectionQuestionnaireAudit',
  NoteSectionAims = 'QuicknoteSectionQuestionnaireAims',
  NoteSectionHamD = 'QuicknoteSectionQuestionnaireHamD',
  NoteSectionMoca = 'QuicknoteSectionQuestionnaireMoca',
  NoteSectionFamilyPsychHx = 'QuicknoteSectionFamilyPsychHx',
  NoteSectionPastPsychHx = 'QuicknoteSectionPastPsychHx',
  NoteSectionPastMedicalHx = 'QuicknoteSectionPastMedicalHx',
  NoteSectionSocialHx = 'QuicknoteSectionSocialHx',
  NoteSectionSubstanceUseHx = 'QuicknoteSectionSubstanceUseHx',
  NoteSectionCodes = 'QuicknoteSectionCodes',
  NoteSectionDiagnosis = 'QuicknoteSectionDiagnosis',
}

export { NoteSectionName }
