const PATIENT_LOOKUP_TABLE_PAGE_SIZE = 20
const PATIENT_LOOKUP_FILTERS_KEY = 'patient-lookup-filters'
const INVALID_RANGE_ERROR = 'Invalid date range'

export {
  PATIENT_LOOKUP_TABLE_PAGE_SIZE,
  PATIENT_LOOKUP_FILTERS_KEY,
  INVALID_RANGE_ERROR,
}
