import { HpiWidgetSchemaType } from './hpi-widget-schema'

const assignSpecificFields = (
  result: HpiWidgetSchemaType,
): Record<string, (value: string) => void> => ({
  ccOtherDetails: (value) => {
    result.ccOtherDetails = value
  },
  subOtherDetails: (value) => {
    result.subOtherDetails = value
  },
  medOtherDetails: (value) => {
    result.medOtherDetails = value
  },
  hpiOther: (value) => {
    result.hpiOther = value
  },
  schizophreniaDelusionValues: (value) => {
    result.schizophreniaDelusionValues = value.split(',')
  },
  schizophreniaHallucinationsValues: (value) => {
    result.schizophreniaHallucinationsValues = value.split(',')
  },
})

const labels = {
  chiefComplaint: {
    depression: 'Depression',
    anxiety: 'Anxiety',
    bipolar: 'Bipolar/Mania',
    ptsd: 'PTSD',
    ocd: 'OCD',
    obsession: 'Obsession/OCD',
    bpd: 'BPD',
    substance: 'Substance',
    adhdInattentive: 'ADHD Inattentive',
    adhdHyperactive: 'ADHD Hyperactive',
    autism: 'Autism',
    conductDisorder: 'Conduct Disorder',
    dementia: 'Dementia',
    schizophrenia: 'Schizophrenia',
    medicationSe: 'Medication SE',
    other: 'ccOther',
  },
  depression: {
    lowMood: 'Low Mood',
    sleepConcerns: 'Sleep Concerns',
    lowInterest: 'Low Interest',
    guilt: 'Guilt',
    poorEnergy: 'Poor Energy',
    poorConcentration: 'Poor Concentration',
    poorMotivation: 'Poor Motivation',
    appetiteConcerns: 'Appetite Concerns',
    hopeless: 'Hopeless',
    slowing: 'Slowing',
    agitation: 'Agitation',
    suicidalThoughts: 'Suicidal Thoughts',
    anger: 'Anger',
  },

  anxiety: {
    feelingAnxious: 'Feeling Anxious',
    worrying: 'Worrying',
    restless: 'Restless',
    fatigue: 'Fatigue',
    muscleTension: 'Muscle Tension',
    irritable: 'Irritable',
    socialAnxiety: 'Social Anxiety',
    panicAttacks: 'Panic Attacks',
    phobia: 'Phobia',
    abnormalFear: 'Abnormal Fear',
  },
  bipolarMania: {
    elevatedMood: 'Elevated Mood',
    distractibility: 'Distractibility',
    goalDirected: 'Goal Directed',
    grandioseDelusions: 'Grandiose Delusions',
    flightOfIdeas: 'Flight Of Ideas',
    lackOfSleep: 'Lack Of Sleep',
    pressuredSpeech: 'Pressured Speech',
    impulsiveRecklessBehavior: 'Impulsive Reckless Behavior',
  },
  ptsd: {
    traumaticEvent: 'Traumatic Event',
    intrusiveMemories: 'Intrusive Memories',
    nightmares: 'Nightmares',
    nightTerrors: 'Night Terrors',
    flashbacks: 'Flashbacks',
    dissociativeEpisodes: 'Dissociative Episodes',
    hypervigilance: 'Hypervigilance',
    avoidance: 'Avoidance',
    startled: 'Startled',
    detachment: 'Detachment',
  },
  obsession: {
    contamination: 'Contamination',
    doubt: 'Doubt',
    somatic: 'Somatic',
    aggression: 'Aggression',
    sexual: 'Sexual',
    checking: 'Checking',
    washing: 'Washing',
    counting: 'Counting',
    hoarding: 'Hoarding',
    picking: 'Picking',
  },
  ocd: {
    checking: 'Checking',
    washing: 'Washing',
    counting: 'Counting',
    hoarding: 'Hoarding',
    picking: 'Picking',
  },
  bpd: {
    blackWhiteThinking: 'Black White Thinking',
    fearOfAbandonment: 'Fear Of Abandonment',
    impulsiveness: 'Impulsiveness',
    moodSwings: 'Mood Swings',
    selfHarm: 'Self-Harm',
    unstableRelationships: 'Unstable Relationships',
    unstableSelfImage: 'Unstable Self-Image',
  },
  substance: {
    tobacco: 'Tobacco',
    alcohol: 'Alcohol',
    opioids: 'Opioids',
    marijuana: 'Marijuana',
    benzos: 'Benzos',
    cocaine: 'Cocaine',
    amphetamine: 'Amphetamine',
    pcp: 'PCP',
    inhalant: 'Inhalant',
    other: 'subOther',
  },
  adhdI: {
    carelessMistakes: 'Careless Mistakes',
    decreasedAttention: 'Decreased Attention',
    doesntListen: "Doesn't Listen",
    hardToFollowInstruction: 'Hard To Follow Instruction',
    difficultyOrganizing: 'Difficulty Organizing',
    difficultyToDoDetailOrientedTasks: 'Difficulty to do Detail Oriented Tasks',
    losesThings: 'Loses Things',
    easilyDistracted: 'Easily Distracted',
    forgetful: 'Forgetful',
  },
  adhdH: {
    fidgeting: 'Fidgeting',
    leavesAssignedSpace: 'Leaves Assigned Space',
    restless: 'Restless',
    hardToEnjoyRelaxing: 'Hard to Enjoy Relaxing',
    onTheGo: 'On the go',
    excessiveTalking: 'Excessive Talking',
    blurtsOutAnswers: 'Blurt Out Answers',
    impatient: 'Impatient',
    interrupts: 'Interrupts',
    behaviorOutbursts: 'Behavior Outbursts',
  },
  autism: {
    fidgeting: 'Delayed Milestones',
    repetitive: 'Repetitive/Restrictive Behaviors',
    regression: 'Regression',
    social: 'Social/Communication Issues',
    aversions: 'Aversions/Special Interests',
    masking: 'Masking',
    emotionalDysregulation: 'Emotional Dysregulation',
  },
  conductDisorder: {
    disciplineIssues: 'Discipline Issues',
    defiance: 'Defiance',
    argumentative: 'Argumentative',
    vengeful: 'Vengeful',
    deceitful: 'Deceitful',
    destructive: 'Destructive',
    disproportionateAnger: 'Disproportionate anger',
    animalCruelty: 'Animal Cruelty',
    manipulative: 'Manipulative',
    suddenOutbursts: 'Sudden Outbursts',
  },
  dementia: {
    memoryLoss: 'Memory Loss',
    confusion: 'Confusion',
    difficultyWithAdls: 'Difficulty with Activities of Daily Living',
    wandering: 'Wandering',
    agitation: 'Agitation',
    ah: 'Auditory Hallucinations',
    vh: 'Visual Hallucinations',
    parkinsonSymptoms: 'Parkinson Symptoms',
  },
  schizophrenia: {
    hallucination: 'Hallucination',
    delusion: 'Delusion',
    disorganized: 'Disorganized',
    anhedonia: 'Anhedonia',
    avolition: 'Avolition',
    catatonia: 'Catatonia',
    suicidalThoughts: 'Suicidal Thoughts',
    homicidalThoughts: 'Homicidal Thoughts',
  },
  medicationSe: {
    giUpset: 'GI Upset',
    sexualSe: 'Sexual SE',
    weightGain: 'Weight Gain',
    headache: 'Headache',
    rash: 'Rash',
    hairLoss: 'Hair loss',
    dystonia: 'Dystonia',
    akathesia: 'Akathesia',
    tardiveDyskinesia: 'Tardive Dyskinesia',
    blurredVision: 'Blurred Vision',
    drowsiness: 'Drowsiness',
    dizzy: 'Dizzy',
    other: 'medOther',
  },
}

const getInitialValues = (): HpiWidgetSchemaType => ({
  chiefComplaint: [],
  depression: [],
  anxiety: [],
  bipolarMania: [],
  ptsd: [],
  obsession: [],
  ocd: [],
  bpd: [],
  substance: [],
  adhdInattentive: [],
  adhdHyperactive: [],
  autism: [],
  conductDisorder: [],
  dementia: [],
  schizophrenia: [],
  medicationSe: [],
  schizophreniaHallucinationsValues: [],
  schizophreniaDelusionValues: [],
  hpiOther: '',
  ccOtherDetails: '',
  subOtherDetails: '',
  medOtherDetails: '',
})

const valueToLabel: { [key: string]: string } = {
  // Chief complaint block
  CC_Depression: labels.chiefComplaint.depression,
  CC_Anxiety: labels.chiefComplaint.anxiety,
  CC_Bipolar: labels.chiefComplaint.bipolar,
  CC_Ptsd: labels.chiefComplaint.ptsd,
  CC_Ocd: labels.chiefComplaint.ocd,
  CC_Obsession: labels.chiefComplaint.obsession,
  CC_Bpd: labels.chiefComplaint.bpd,
  CC_Substance: labels.chiefComplaint.substance,
  CC_Adhdi: labels.chiefComplaint.adhdInattentive,
  CC_Adhdh: labels.chiefComplaint.adhdHyperactive,
  CC_Autism: labels.chiefComplaint.autism,
  CC_ConductDisorder: labels.chiefComplaint.conductDisorder,
  CC_Dementia: labels.chiefComplaint.dementia,
  CC_Schizophrenia: labels.chiefComplaint.schizophrenia,
  CC_MedicationSe: labels.chiefComplaint.medicationSe,
  CC_Other: labels.chiefComplaint.other,

  // Depression block
  DEP_LowMood: labels.depression.lowMood,
  DEP_SleepConcerns: labels.depression.sleepConcerns,
  DEP_LowInterest: labels.depression.lowInterest,
  DEP_Guilt: labels.depression.guilt,
  DEP_PoorEnergy: labels.depression.poorEnergy,
  DEP_PoorConcentration: labels.depression.poorConcentration,
  DEP_PoorMotivation: labels.depression.poorMotivation,
  DEP_AppetiteConcerns: labels.depression.appetiteConcerns,
  DEP_Hopeless: labels.depression.hopeless,
  DEP_Slowing: labels.depression.slowing,
  DEP_Agitation: labels.depression.agitation,
  DEP_SuicidalThoughts: labels.depression.suicidalThoughts,
  DEP_Anger: labels.depression.anger,

  // Anxiety block
  ANX_FeelingAnxious: labels.anxiety.feelingAnxious,
  ANX_Worrying: labels.anxiety.worrying,
  ANX_Restless: labels.anxiety.restless,
  ANX_Fatigue: labels.anxiety.fatigue,
  ANX_MuscleTension: labels.anxiety.muscleTension,
  ANX_Irritable: labels.anxiety.irritable,
  ANX_SocialAnxiety: labels.anxiety.socialAnxiety,
  ANX_PanicAttacks: labels.anxiety.panicAttacks,
  ANX_Phobia: labels.anxiety.phobia,
  ANX_AbnormalFear: labels.anxiety.abnormalFear,

  // Bipolar/Mania block
  MAN_ElevatedMood: labels.bipolarMania.elevatedMood,
  MAN_Distractibility: labels.bipolarMania.distractibility,
  MAN_GoalDirected: labels.bipolarMania.goalDirected,
  MAN_GrandioseDelusions: labels.bipolarMania.grandioseDelusions,
  MAN_FlightOfIdeas: labels.bipolarMania.flightOfIdeas,
  MAN_LackOfSleep: labels.bipolarMania.lackOfSleep,
  MAN_PressuredSpeech: labels.bipolarMania.pressuredSpeech,
  MAN_ImpulsiveRecklessBehavior: labels.bipolarMania.impulsiveRecklessBehavior,

  // PTSD block
  PTS_TraumaticEvent: labels.ptsd.traumaticEvent,
  PTS_IntrusiveMemories: labels.ptsd.intrusiveMemories,
  PTS_Nightmares: labels.ptsd.nightmares,
  PTS_NightTerrors: labels.ptsd.nightTerrors,
  PTS_Flashbacks: labels.ptsd.flashbacks,
  PTS_DissociativeEpisodes: labels.ptsd.dissociativeEpisodes,
  PTS_Hypervigilance: labels.ptsd.hypervigilance,
  PTS_Avoidance: labels.ptsd.avoidance,
  PTS_Startled: labels.ptsd.startled,
  PTS_Detachment: labels.ptsd.detachment,

  // Obsession block
  OBS_Contamination: labels.obsession.contamination,
  OBS_Doubt: labels.obsession.doubt,
  OBS_Somatic: labels.obsession.somatic,
  OBS_Aggression: labels.obsession.aggression,
  OBS_Sexual: labels.obsession.sexual,
  OBS_Checking: labels.obsession.checking,
  OBS_Washing: labels.obsession.washing,
  OBS_Counting: labels.obsession.counting,
  OBS_Hoarding: labels.obsession.hoarding,
  OBS_Picking: labels.obsession.picking,

  // OCD block
  OCD_Checking: labels.ocd.checking,
  OCD_Washing: labels.ocd.washing,
  OCD_Counting: labels.ocd.counting,
  OCD_Hoarding: labels.ocd.hoarding,
  OCD_Picking: labels.ocd.picking,

  // Borderline Personality disorder block
  BPD_BlackWhiteThinking: labels.bpd.blackWhiteThinking,
  BPD_FearOfAbandonment: labels.bpd.fearOfAbandonment,
  BPD_Impulsiveness: labels.bpd.impulsiveness,
  BPD_MoodSwings: labels.bpd.moodSwings,
  BPD_SelfHarm: labels.bpd.selfHarm,
  BPD_UnstableRelationships: labels.bpd.unstableRelationships,
  BPD_UnstableSelfImage: labels.bpd.unstableSelfImage,

  // Substance block
  SUB_Tobacco: labels.substance.tobacco,
  SUB_Alcohol: labels.substance.alcohol,
  SUB_Opioids: labels.substance.opioids,
  SUB_Marijuana: labels.substance.marijuana,
  SUB_Benzos: labels.substance.benzos,
  SUB_Cocaine: labels.substance.cocaine,
  SUB_Amphetamine: labels.substance.amphetamine,
  SUB_Pcp: labels.substance.pcp,
  SUB_Inhalant: labels.substance.inhalant,
  SUB_Other: labels.substance.other,

  // ADHD Inattentive block
  ADI_CarelessMistakes: labels.adhdI.carelessMistakes,
  ADI_DecreasedAttention: labels.adhdI.decreasedAttention,
  ADI_DoesntListen: labels.adhdI.doesntListen,
  ADI_HardToFollowInstruction: labels.adhdI.hardToFollowInstruction,
  ADI_DifficultyOrganizing: labels.adhdI.difficultyOrganizing,
  ADI_DifficultyToDoDetailOrientedTasks:
    labels.adhdI.difficultyToDoDetailOrientedTasks,
  ADI_LosesThings: labels.adhdI.losesThings,
  ADI_EasilyDistracted: labels.adhdI.easilyDistracted,
  ADI_Forgetful: labels.adhdI.forgetful,

  // ADHD Hyperactive block
  ADH_Fidgeting: labels.adhdH.fidgeting,
  ADH_LeavesAssignedSpace: labels.adhdH.leavesAssignedSpace,
  ADH_Restless: labels.adhdH.restless,
  ADH_HardToEnjoyRelaxing: labels.adhdH.hardToEnjoyRelaxing,
  ADH_OnTheGo: labels.adhdH.onTheGo,
  ADH_ExcessiveTalking: labels.adhdH.excessiveTalking,
  ADH_BlurtsOutAnswers: labels.adhdH.blurtsOutAnswers,
  ADH_Impatient: labels.adhdH.impatient,
  ADH_Interrupts: labels.adhdH.interrupts,
  ADH_BehaviorOutbursts: labels.adhdH.behaviorOutbursts,

  // Autism Block
  AUT_Fidgeting: labels.autism.fidgeting,
  AUT_Repetitive: labels.autism.repetitive,
  AUT_Regression: labels.autism.regression,
  AUT_Social: labels.autism.social,
  AUT_Aversions: labels.autism.aversions,
  AUT_Masking: labels.autism.masking,
  AUT_EmotionalDysregulation: labels.autism.emotionalDysregulation,

  // Conduct Disorder Block
  CD_DisciplineIssues: labels.conductDisorder.disciplineIssues,
  CD_Defiance: labels.conductDisorder.defiance,
  CD_Argumentative: labels.conductDisorder.argumentative,
  CD_Vengeful: labels.conductDisorder.vengeful,
  CD_Deceitful: labels.conductDisorder.deceitful,
  CD_Destructive: labels.conductDisorder.destructive,
  CD_DisproportionateAnger: labels.conductDisorder.disproportionateAnger,
  CD_AnimalCruelty: labels.conductDisorder.animalCruelty,
  CD_Manipulative: labels.conductDisorder.manipulative,
  CD_SuddenOutbursts: labels.conductDisorder.suddenOutbursts,
  // Dementia Block
  DEM_MemoryLoss: labels.dementia.memoryLoss,
  DEM_Confusion: labels.dementia.confusion,
  DEM_DifficultyWithAdls: labels.dementia.difficultyWithAdls,
  DEM_Wandering: labels.dementia.wandering,
  DEM_Agitation: labels.dementia.agitation,
  DEM_Ah: labels.dementia.ah,
  DEM_Vh: labels.dementia.vh,
  DEM_ParkinsonSymptoms: labels.dementia.parkinsonSymptoms,

  // Schizophrenia Block
  SCH_Hallucination: labels.schizophrenia.hallucination,
  SCH_Delusion: labels.schizophrenia.delusion,
  SCH_Disorganized: labels.schizophrenia.disorganized,
  SCH_Anhedonia: labels.schizophrenia.anhedonia,
  SCH_Avolition: labels.schizophrenia.avolition,
  SCH_Catatonia: labels.schizophrenia.catatonia,
  SCH_SuicidalThoughts: labels.schizophrenia.suicidalThoughts,
  SCH_HomicidalThoughts: labels.schizophrenia.homicidalThoughts,

  // Medication SE Block
  MED_GiUpset: labels.medicationSe.giUpset,
  MED_SexualSe: labels.medicationSe.sexualSe,
  MED_WeightGain: labels.medicationSe.weightGain,
  MED_Headache: labels.medicationSe.headache,
  MED_Rash: labels.medicationSe.rash,
  MED_HairLoss: labels.medicationSe.hairLoss,
  MED_Dystonia: labels.medicationSe.dystonia,
  MED_Akathesia: labels.medicationSe.akathesia,
  MED_TardiveDyskinesia: labels.medicationSe.tardiveDyskinesia,
  MED_BlurredVision: labels.medicationSe.blurredVision,
  MED_Drowsiness: labels.medicationSe.drowsiness,
  MED_Dizzy: labels.medicationSe.dizzy,
  MED_Other: labels.medicationSe.other,
  // Other block
  hpiOther: 'hpiOther',
  ccOtherDetails: 'ccOtherDetails',
  subOtherDetails: 'subOtherDetails',
  medOtherDetails: 'medOtherDetails',
  schizophreniaHallucinationsValues: 'schizophreniaHallucinationsValues',
  schizophreniaDelusionValues: 'schizophreniaDelusionValues',
}

const optionsValueToLabel: { [key: string]: string } = {
  //DELUSION_OPTIONS
  grandiose: 'Grandiose',
  ofReference: 'OfReference',
  erotomania: 'Erotomania',
  persecutory: 'Persecutory',
  jealous: 'Jealous',
  bizarre: 'Bizarre',
  mixed: 'Mixed',
  nihilistic: 'Nihilistic',
  thoughtBroadcasting: 'ThoughtBroadcasting',
  guilt: 'Guilt',
  thoughtInsertion: 'ThoughtInsertion',
  persecution: 'Persecution',
  unspecified: 'Unspecified',
  infidelity: 'Infidelity',
  Somatic: 'Somatic',
  misidentificationSyndrome: 'MisidentificationSyndrome',
  auditory: 'Auditory',
  visual: 'Visual',
  Olfactory: 'Olfactory',
  tactile: 'Tactile',
  gustatory: 'Gustatory',
  chiefComplaint: 'Chief Complaint',
  depression: 'Depression',
  anxiety: 'Anxiety',
  bipolarMania: ' Bipolar/Mania',
  ptsd: 'PTSD',
  obsession: 'Obsession/OCD (Obsessive Compulsive Disorder)',
  ocd: 'OCD',
  bpd: 'BPD',
  substance: 'Substance',
  adhdInattentive: 'Adhd Inattentive',
  adhdHyperactive: 'Adhd Hyperactive',
  autism: 'Autism',
  conductDisorder: 'Conduct Disorder',
  dementia: 'Dementia',
  schizophrenia: 'Schizophrenia',
  medicationSe: 'Medication SE',
}

export {
  assignSpecificFields,
  getInitialValues,
  valueToLabel,
  optionsValueToLabel,
  labels,
}
