// Generated by https://quicktype.io

export interface AssessmentAndTreatment {
  id?: string
  metadata?: Metadata
  recordStatus?: string
  assessmentPlanDate?: string
  status?: string
  patientId?: number
  noteId?: number
  patientAssessments?: PatientAssessment[]
  patientPlanOfTreatments?: PatientPlanOfTreatment[]
}

export interface Metadata {
  createdOn: string
  createdBy: number
  createdByFullName: string
  updatedOn: string
  updatedBy: number
  updatedByFullName: string
  deletedOn: string
  deletedBy: number
  deletedByFullName: string
}

export interface PatientAssessment {
  id?: string
  metadata?: Metadata
  recordStatus?: string
  patientAssessmentPlanId?: string
  assessment?: string
  uniqId?: string
}

export interface PatientPlanOfTreatment {
  id?: string
  metadata?: Metadata
  recordStatus?: string
  patientAssessmentPlanId?: string
  planDate?: string
  planOfTreatmentNotes?: string
  symptomCode: string
  symptomCodesetUsed: string
  symptomCodeDescription: string
  planType: string
  uniqId?: string
}

export interface PatientParams {
  patientId: number
  noteId: number
}

export const TYPES = [
  { value: 'Text', label: 'Text' },
  { value: 'Lab Test', label: 'Lab Test' },
  { value: 'Medication', label: 'Medication' },
  { value: 'Encounter', label: 'Encounter' },
]

export const STATUSES = [
  { value: 'Active', label: 'Active' },
  { value: 'Resolved', label: 'Resolved' },
]

export interface IcdCodes {
  id: number
  metadata: Metadata
  code: string
  description: string
  isFavorite?: boolean
  isActive?: boolean
}
export interface IcdFilters {
  codeOrDescription?: string
}

export interface Snomed {
  codeSystemName: string
  displayName: string
  version: string
  oid: string
  codes: SnomedCode[]
}

export interface SnomedCode {
  code: string
  displayName: string
}
