  # CONFIG: ASP NET

  - name: RUN_ENVIRONMENT
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: aspNetCoreEnvironment

  - name: ASPNETCORE_URLS
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: aspNetCoreUrls

  # CONFIG: Caching

  - name: APPSETTINGS_Caching__CodeSetCacheExpireMinutes
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: cachingCodeSetCacheExpireMinutes

  # CONFIG: APPs

  - name: APP_ENV
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: aspNetCoreEnvironment

  - name: CLINICAL_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: reactAppClinicalUrl

  - name: GALAXY_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: reactAppGalaxyUrl

  - name: PATIENT_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: reactAppPatientUrl

  - name: REVCYCLE_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: reactAppRevCycleUrl

  - name: PLATFORM_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: reactAppPlatformUrl

  - name: API_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: apiUrl

  - name: AUTH_API_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: authApiUrl

  # SECRETS: Google

  - name: GOOGLE_MAPS_API_KEY
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: googleMapsKey

  # SECRETS: Stripe

  - name: STRIPE_PUBLISHABLE_KEY
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: stripePublishableApiKey

  - name: STRIPE_API_KEY
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: stripeApiKey

  # SECRETS: Recaptcha

  - name: RECAPTCHA_V2_KEY
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: recaptchaV2Key

  # SECRETS: Mapbox

  - name: MAPBOX_ACCESS_TOKEN
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: mapboxAccessToken
