environment: ""
image:
  repository: ''
  pullPolicy: Always
  tag: ''

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}

podAnnotations:
  config.linkerd.io/proxy-cpu-limit: "1"
  config.linkerd.io/proxy-cpu-request: "70m"
  config.linkerd.io/proxy-memory-limit: "1Gi"
  config.linkerd.io/proxy-memory-request: "8Mi"

podSecurityContext: {}

securityContext: {}

container:
  portName: http
  containerPort: 3000
  protocol: TCP

service:
  enabled: true
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    # use issuer instead of cluster-issuer for namespace scope
    # cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/service-upstream: "true"
  hosts:
  - host: ui.integration.psychplus.dev
    paths:
    - path: /
      pathType: Prefix
  tls:
  - hosts:
    - ui.integration.psychplus.dev
    secretName: ui-psychplus-io-tls

ingressAuth:
  enabled: false

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 128m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

startupProbeEnabled: false
startupProbe:
  httpGet:
    path: /healthz/liveness_CF796DFC-2BE3-415f-9F86-63C29517DF8B
    port: http
  periodSeconds: 30
  timeoutSeconds: 30

livenessProbeEnabled: false
livenessProbe:
  httpGet:
    path: /healthz/liveness_CF796DFC-2BE3-415f-9F86-63C29517DF8B
    port: http
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbeEnabled: false
readinessProbe:
  httpGet:
    path: /healthz/readiness_CF796DFC-2BE3-415f-9F86-63C29517DF8B
    port: http
  periodSeconds: 10
  timeoutSeconds: 5

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodepool
          operator: NotIn
          values:
          - system

env:
  - name: APP_CODE
    value: "p+patient-ui"

  - name: APP_PATH
    value: ""

  - name: APP_VERSION
    value: "1.0.0"

  # CONFIG: APPs

  - name: APP_ENV
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: aspNetCoreEnvironment

  - name: API_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: apiUrl

  - name: CLINICAL_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: reactAppClinicalUrl

  - name: PATIENT_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: reactAppPatientUrl

  - name: REVCYCLE_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: reactAppRevCycleUrl

  - name: PLATFORM_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: reactAppPlatformUrl

  # CONFIG: ASP NET

  - name: RUN_ENVIRONMENT
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: aspNetCoreEnvironment

  - name: ASPNETCORE_URLS
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: aspNetCoreUrls

  # AUTH

  - name: AUTH_API_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: authApiUrl

  - name: AUTH_ACCESS_TOKEN_COOKIE_NAME
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: authAccessTokenCookieName

  - name: AUTH_ACCESS_TOKEN_EXPIRY_COOKIE_NAME
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: authAccessTokenExpiryCookieName

  - name: AUTH_REFRESH_TOKEN_COOKIE_NAME
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: authRefreshTokenCookieName

  - name: AUTH_USER_COOKIE_NAME
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: authUserCookieName

  # CONFIG: Caching

  - name: APPSETTINGS_Caching__CodeSetCacheExpireMinutes
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: cachingCodeSetCacheExpireMinutes

  # CONFIG: SCRIPTSURE

  - name: SCRIPTSURE_BASE_APPLICATION_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: scriptSureBaseApplicationUrl

  - name: SCRIPTSURE_BASE_PLATFORM_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: scriptSureBasePlatformUrl

  - name: SCRIPTSURE_SESSION_COOKIE_NAME
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: scriptSureSessionCookieName

  - name: SCRIPTSURE_SESSION_COOKIE_CREATED_AT
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: scriptSureSessionCookieCreateAt

  # SECRETS: Google

  - name: GOOGLE_MAPS_API_KEY
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: googleMapsKey

  # SECRETS: SCRIPTSURE

  - name: SCRIPTSURE_API_KEY
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: scriptSureApiKey

  - name: SCRIPTSURE_API_SECRET
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: scriptSureApiSecret

  - name: SCRIPTSURE_ENCRYPTION_KEY
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: scriptSureEncryptionKey

  - name: SCRIPTSURE_PATIENT_PORTAL_USER_EMAIL
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: scriptSurePatientPortalUserEmail

  - name: SCRIPTSURE_PATIENT_PORTAL_USER_EMAIL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: scriptSurePatientPortalUserPassword

  # SECRETS: Stripe

  - name: STRIPE_PUBLISHABLE_KEY
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: stripePublishableApiKey

  - name: STRIPE_API_KEY
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: stripeApiKey

  # SECRETS: Recaptcha

  - name: RECAPTCHA_V2_KEY
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: recaptchaV2Key

  # SECRETS: Mapbox

  - name: MAPBOX_ACCESS_TOKEN
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: mapboxAccessToken
