const defaultValues = {
  startingDate: undefined,
  endingDate: undefined,
  name: '',
  age: [],
  gender: '',
  dateOfBirth: undefined,
  patientStatuses: [],
  locationIds: [],
  serviceIds: [],
  providerIds: [],
  providerTypes: [],
  unitIds: [],
  roomIds: [],
  stateIds: [],
  groupIds: [],
  servicesOffered: [],
  primaryInsuranceNames: [],
  secondaryInsuranceNames: [],
  visitTypes: [],
  visitSequences: [],
  visitMediums: [],
  appointmentStatuses: [],
  patientInsuranceVerificationStatuses: [],
  diagnosisCode: '',
  cptCode: '',
  dateOfAdmissionStart: undefined,
  dateOfAdmissionEnd: undefined,
  lengthOfStayMin: null,
  lengthOfStayMax: null,
  lastCoverageDateStart: undefined,
  lastCoverageDateEnd: undefined,
  legalStatuses: [],
  copayDueMin: null,
  copayDueMax: null,
  coInsuranceDueMin: null,
  coInsuranceDueMax: null,
  balanceDueMin: null,
  balanceDueMax: null,
  noteSignedStatuses: [],
}

export { defaultValues }
