const CODE_SET_SERVICE_OFFERED = 'ServicesOffered'
const CODE_SET_SERVICES_STATUS = 'ServicesStatus'
const CODE_SET_ATTRIBUTE_IS_EMERGENCY_STATUS_ALLOWED =
  'IsEmergencyStatusAllowed'
const DEFAULT_REFERRAL_SERVICE_STATUS = 'Routine'
const EMERGENCY_REFERRAL_SERVICE_STATUS = 'Emergency'

export {
  CODE_SET_SERVICE_OFFERED,
  CODE_SET_SERVICES_STATUS,
  CODE_SET_ATTRIBUTE_IS_EMERGENCY_STATUS_ALLOWED,
  DEFAULT_REFERRAL_SERVICE_STATUS,
  EMERGENCY_REFERRAL_SERVICE_STATUS,
}
