// Header keys
const HEADER_PSYCHPLUS_APPLICATION = 'PsychPlus-Application'
const HEADER_PSYCHPLUS_APP_VERSION = 'PsychPlus-AppVersion'
const HEADER_PSYCHPLUS_RUN_ENVIRONMENT = 'PsychPlus-RunEnvironment'
const HEADER_PSYCHPLUS_DEVICE = 'PsychPlus-Device'
const HEADER_AUTHORIZATION = 'Authorization'
const HEADER_CONTENT_TYPE = 'Content-Type'
const HEADER_USER_AGENT = 'user-agent'
const HEADER_X_URL = 'x-url'

// Header values
const CONTENT_TYPE_APPLICATION_JSON = 'application/json'
const BEARER_AUTHENTICATION = 'Bearer'

export {
  HEADER_PSYCHPLUS_APPLICATION,
  HEADER_PSYCHPLUS_APP_VERSION,
  HEADER_PSYCHPLUS_RUN_ENVIRONMENT,
  HEADER_PSYCHPLUS_DEVICE,
  HEADER_AUTHORIZATION,
  HEADER_CONTENT_TYPE,
  HEADER_USER_AGENT,
  HEADER_X_URL,
  CONTENT_TYPE_APPLICATION_JSON,
  BEARER_AUTHENTICATION,
}
