image:
  repository: ''
  pullPolicy: Always
  tag: ''

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}

podAnnotations:
  config.linkerd.io/proxy-cpu-limit: "1"
  config.linkerd.io/proxy-cpu-request: "70m"
  config.linkerd.io/proxy-memory-limit: "1Gi"
  config.linkerd.io/proxy-memory-request: "8Mi"

podSecurityContext: {}

securityContext: {}

container:
  portName: http
  containerPort: 3002
  protocol: TCP

service:
  enabled: true
  type: ClusterIP
  port: 3002

ingress:
  enabled: true
  className: nginx
  annotations:
    # use issuer instead of cluster-issuer for namespace scope
    cert-manager.io/cluster-issuer: letsencrypt
    # nginx.ingress.kubernetes.io/app-root: /revcycle
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/service-upstream: "true"
  hosts:
  - host: ui.integration.psychplus.dev
    paths:
    - path: /revcycle(/|$)(.*)
      pathType: ImplementationSpecific
  tls:
  - hosts:
    - ui.integration.psychplus.dev
    secretName: ui-psychplus-io-tls

ingressAuth:
  enabled: false

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 128m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

startupProbeEnabled: false
startupProbe:
  httpGet:
    path: /health/liveness_73C8DD3A-DF35-43f6-BA56-F3944E006637
    port: http
  periodSeconds: 30
  timeoutSeconds: 30

livenessProbeEnabled: false
livenessProbe:
  httpGet:
    path: /health/liveness_73C8DD3A-DF35-43f6-BA56-F3944E006637
    port: http
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbeEnabled: false
readinessProbe:
  httpGet:
    path: /health/readiness_73C8DD3A-DF35-43f6-BA56-F3944E006637
    port: http
  periodSeconds: 10
  timeoutSeconds: 1

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}

env:
  - name: APP_CODE
    value: "p+revcycle-ui"

  - name: APP_PATH
    value: "revcycle"

  - name: APP_VERSION
    value: "1.0.0"

  # CONFIG: ASP NET

  - name: RUN_ENVIRONMENT
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: aspNetCoreEnvironment

  - name: ASPNETCORE_URLS
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: aspNetCoreUrls
  
  # CONFIG: Caching

  - name: APPSETTINGS_Caching__CodeSetCacheExpireMinutes
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: cachingCodeSetCacheExpireMinutes

  # CONFIG: APPs

  - name: APP_ENV
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: aspNetCoreEnvironment

  - name: CLINICAL_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: reactAppClinicalUrl

  - name: PATIENT_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: reactAppPatientUrl

  - name: REVCYCLE_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: reactAppRevCycleUrl

  - name: PLATFORM_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: reactAppPlatformUrl

  - name: API_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: apiUrl

  - name: AUTH_API_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: authApiUrl

  # SECRETS: Google

  - name: GOOGLE_MAPS_API_KEY
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: googleMapsKey

  # SECRETS: Stripe

  - name: STRIPE_PUBLISHABLE_KEY
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: stripePublishableApiKey

  # SECRETS: Recaptcha

  - name: RECAPTCHA_V2_KEY
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: recaptchaV2Key

  # SECRETS: Mapbox

  - name: MAPBOX_ACCESS_TOKEN
    valueFrom:
      secretKeyRef:
        name: ehr-secrets
        key: mapboxAccessToken
