const TOGRA_BLUE_LABEL =
  'You have 16 minutes to complete as many of the questions as possible. Answer each question to the best of your ability. '

const TEXT_QUESTIONS: Record<string, { label: string; value: string }[]> = {
  Q3: [
    { label: 'Absence', value: 'a' },
    { label: 'Conscious', value: 'b' },
    { label: 'Covert', value: 'c' },
    { label: 'Omniscience', value: 'd' },
    { label: 'Overt', value: 'e' },
  ],
  Q5: [
    { label: 'Belt', value: 'a' },
    { label: 'Jeans', value: 'b' },
    { label: 'Pants', value: 'c' },
    { label: 'Slacks', value: 'd' },
    { label: 'Trousers', value: 'e' },
  ],
  Q8: [
    { label: 'Amiable', value: 'a' },
    { label: 'Colleague', value: 'b' },
    { label: 'Foe', value: 'c' },
    { label: 'Foible', value: 'd' },
    { label: 'Frond', value: 'e' },
  ],
  Q9: [
    { label: 'Actual', value: 'a' },
    { label: 'Literal', value: 'b' },
    { label: 'Metaphorical', value: 'c' },
    { label: 'Real', value: 'd' },
    { label: 'True', value: 'e' },
  ],
  Q10: [
    { label: 'Cry', value: 'a' },
    { label: 'Face', value: 'b' },
    { label: 'Happy', value: 'c' },
    { label: 'Laugh', value: 'd' },
    { label: 'Sad', value: 'e' },
  ],
  Q13: [
    { label: '10', value: 'a' },
    { label: '12', value: 'b' },
    { label: '14', value: 'c' },
    { label: '16', value: 'd' },
    { label: '18', value: 'e' },
  ],
  Q15: [
    { label: 'Bulky', value: 'a' },
    { label: 'Little', value: 'b' },
    { label: 'Puny', value: 'c' },
    { label: 'Slight', value: 'd' },
    { label: 'Small', value: 'e' },
  ],
  Q17: [
    { label: 'Able', value: 'a' },
    { label: 'Adept', value: 'b' },
    { label: 'Clumsy', value: 'c' },
    { label: 'Fit', value: 'd' },
    { label: 'Skilled', value: 'e' },
  ],
  Q18: [
    { label: '106', value: 'a' },
    { label: '102', value: 'b' },
    { label: '98', value: 'c' },
    { label: '96', value: 'd' },
    { label: '94', value: 'e' },
  ],
  Q19: [
    { label: '20', value: 'a' },
    { label: '24', value: 'b' },
    { label: '32', value: 'c' },
    { label: '40', value: 'd' },
    { label: '48', value: 'e' },
  ],
  Q22: [
    { label: '5/8', value: 'a' },
    { label: '3/4', value: 'b' },
    { label: '2/3', value: 'c' },
    { label: '4/5', value: 'd' },
    { label: '2/8', value: 'e' },
  ],
  Q23: [
    { label: '1', value: 'a' },
    { label: '2', value: 'b' },
    { label: '3', value: 'c' },
    { label: '4', value: 'd' },
    { label: '5', value: 'e' },
  ],
  Q24: [
    { label: '3', value: 'a' },
    { label: '5', value: 'b' },
    { label: '7', value: 'c' },
    { label: '9', value: 'd' },
    { label: '11', value: 'e' },
  ],
  Q27: [
    { label: '106', value: 'a' },
    { label: '102', value: 'b' },
    { label: '98', value: 'c' },
    { label: '96', value: 'd' },
    { label: '94', value: 'e' },
  ],
  Q28: [
    { label: '800', value: 'a' },
    { label: '865', value: 'b' },
    { label: '860', value: 'c' },
    { label: '870', value: 'd' },
    { label: '900', value: 'e' },
  ],
  Q34: [
    { label: '101, 98', value: 'a' },
    { label: '102, 99', value: 'b' },
    { label: '94, 98', value: 'c' },
    { label: '98, 102', value: 'd' },
    { label: '103, 99', value: 'e' },
  ],
  Q36: [
    { label: '14 3/14', value: 'a' },
    { label: '4 3/14', value: 'b' },
    { label: '12 2/3', value: 'c' },
    { label: '4 2/3', value: 'd' },
    { label: '4 ¾', value: 'e' },
  ],
  Q38: [
    { label: 'Brighten', value: 'a' },
    { label: 'Confuse', value: 'b' },
    { label: 'Deceive', value: 'c' },
    { label: 'Dim', value: 'd' },
    { label: 'Enlighten', value: 'e' },
  ],
  Q42: [
    { label: '25', value: 'a' },
    { label: '26', value: 'b' },
    { label: '27', value: 'c' },
    { label: '28', value: 'd' },
    { label: '29', value: 'e' },
  ],
  Q43: [
    { label: '70', value: 'a' },
    { label: '60', value: 'b' },
    { label: '30', value: 'c' },
    { label: '10', value: 'd' },
    { label: '0', value: 'e' },
  ],
  Q44: [
    { label: 'Chronometer', value: 'a' },
    { label: 'Clock', value: 'b' },
    { label: 'Pentameter', value: 'c' },
    { label: 'Sundial', value: 'd' },
    { label: 'Watch', value: 'e' },
  ],
  Q45: [
    { label: '-1', value: 'a' },
    { label: '0', value: 'b' },
    { label: '3', value: 'c' },
    { label: '5', value: 'd' },
    { label: '7', value: 'e' },
  ],
  Q46: [
    { label: '50', value: 'a' },
    { label: '175', value: 'b' },
    { label: '225', value: 'c' },
    { label: '250', value: 'd' },
    { label: '300', value: 'e' },
  ],
  Q48: [
    { label: '5:8', value: 'a' },
    { label: '5:7', value: 'b' },
    { label: '1:4', value: 'c' },
    { label: '8:20', value: 'd' },
    { label: '1:5', value: 'e' },
  ],
  Q49: [
    { label: '-3', value: 'a' },
    { label: '3', value: 'b' },
    { label: '2 1/3', value: 'c' },
    { label: '1/3', value: 'd' },
    { label: '10/3', value: 'e' },
  ],
  Q50: [
    { label: 'Arch', value: 'a' },
    { label: 'Dab', value: 'b' },
    { label: 'Fleck', value: 'c' },
    { label: 'Iota', value: 'd' },
    { label: 'Whit', value: 'e' },
  ],
  Q52: [
    { label: '0', value: 'a' },
    { label: '1', value: 'b' },
    { label: '4', value: 'c' },
    { label: '16', value: 'd' },
    { label: '36', value: 'e' },
  ],
  Q55: [
    { label: '49', value: 'a' },
    { label: '48', value: 'b' },
    { label: '47', value: 'c' },
    { label: '46', value: 'd' },
    { label: '45', value: 'e' },
  ],
  Q57: [
    { label: 'Endow', value: 'a' },
    { label: 'Expropriate', value: 'b' },
    { label: 'Lerp', value: 'c' },
    { label: 'Irritate', value: 'd' },
    { label: 'Undulate', value: 'e' },
  ],
  Q58: [
    { label: '4', value: 'a' },
    { label: '8', value: 'b' },
    { label: '12', value: 'c' },
    { label: '16', value: 'd' },
    { label: '32', value: 'e' },
  ],
  Q60: [
    { label: 'Bluff', value: 'a' },
    { label: 'Hoax', value: 'b' },
    { label: 'Literate', value: 'c' },
    { label: 'Metaphorical', value: 'd' },
    { label: 'Truth', value: 'e' },
  ],
}

const ANSWERS = {
  Q1: 'c',
  Q2: 'a',
  Q3: 'a',
  Q4: 'a',
  Q5: 'a',
  Q6: 'e',
  Q7: 'e',
  Q8: 'c',
  Q9: 'c',
  Q10: 'b',
  Q11: 'c',
  Q12: 'b',
  Q13: 'd',
  Q14: 'a',
  Q15: 'a',
  Q16: 'a',
  Q17: 'c',
  Q18: 'b',
  Q19: 'c',
  Q20: 'b',
  Q21: 'd',
  Q22: 'b',
  Q23: 'b',
  Q24: 'd',
  Q25: 'd',
  Q26: 'd',
  Q27: 'e',
  Q28: 'c',
  Q29: 'd',
  Q30: 'd',
  Q31: 'c',
  Q32: 'c',
  Q33: 'c',
  Q34: 'a',
  Q35: 'a',
  Q36: 'd',
  Q37: 'a',
  Q38: 'e',
  Q39: 'e',
  Q40: 'b',
  Q41: 'd',
  Q42: 'c',
  Q43: 'a',
  Q44: 'c',
  Q45: 'e',
  Q46: 'd',
  Q47: 'c',
  Q48: 'c',
  Q49: 'a',
  Q50: 'a',
  Q51: 'b',
  Q52: 'b',
  Q53: 'c',
  Q54: 'd',
  Q55: 'c',
  Q56: 'a',
  Q57: 'a',
  Q58: 'd',
  Q59: 'a',
  Q60: 'e',
}

const QUESTIONS = [
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the picture from the bottom row that best completes the top row.',
  'Which word is the opposite of presence?',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the best answer. Which word does not belong?',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the best answer. Which work is the opposite of friend?',
  'Choose the best answer. Which word does not belong?',
  'Choose the best answer. Which word does not belong?',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the best answer. Select the missing number in the series: 2, 4, 8, ___, 32, 64',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the best answer. Which word does not belong?',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the best answer. Which word does not belong?',
  'Choose the best answer. Select the missing number in the series: 100, 97, 101, 98, ___',
  'Choose the best answer. Select the missing number in the series: 2, 4, 8 16, ____',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the best answer. What is 12/16 in simplest terms?',
  'Choose the best answer. How many fourths are in one half of a cake?',
  'Choose the best answer. A teacher schedules ½-hour meetings with each of her students for 4 ½ hours each day. How many students can she see in one day?',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the picture from the bottom row that best completes the top row',
  'Choose the best answer. Select the missing number in the series:  100, 96, 99, 95, 98, ____',
  'Choose the best answer. Round 863 to the nearest ten.',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the best answer. Select the missing numbers in the series. 99, 96, 100, 97, __, __',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the best answer. Convert 14/3 to a mixed number.',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the best answer. Which word is the opposite of baffle?',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the best answer. Select the missing number in the series: 39, 34, 30, ___, 25',
  'Choose the best answer. Select the missing number in the series:  50, 40, 60, 30, ___, 20',
  'Choose the best answer. Which word does not belong?',
  'Choose the best answer. Select the number that correctly completes the comparison: 1, 1, 3, 2, __ :: 2, 3, 1, 1, 7',
  'Choose the best answer. According to the legend on a map, one inch is equal to 150 miles. If the distance between two cities is 1 2/3 inches on the map, how far is the actual distance in miles?',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the best answer. A box has 8 blue marbles, 5 yellow marbles, and 7 black marbles. What is the ratio of yellow marbles to the total number of marbles?',
  'Choose the best answer.',
  'Choose the best answer. Which word does not belong?',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the best answer. Select the number that correctly completes this analogy: 0:1 is to 0: __ as 2:3 is to 4:9',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the best answer. Select the missing number in the series: 77, 65, 55, __, 41',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the best answer. Which word is the opposite of usurp?',
  'Choose the best answer. If two machines can finish a job in 8 hours, how many of the same machines would be necessary to finish the job in just 1 hour?',
  'Choose the picture from the bottom row that best completes the top row.',
  'Choose the best answer. Which word is the opposite of canard?',
].map((question, index) => ({
  id: `Q${index + 1}`,
  question,
  value: 0,
  radio: !!TEXT_QUESTIONS[`Q${index + 1}`],
  options: TEXT_QUESTIONS[`Q${index + 1}`]
    ? TEXT_QUESTIONS[`Q${index + 1}`]
    : [
        { label: 'A', value: 'a' },
        { label: 'B', value: 'b' },
        { label: 'C', value: 'c' },
        { label: 'D', value: 'd' },
        { label: 'E', value: 'e' },
      ],
}))

const TOTAL_QUESTIONS = QUESTIONS.length

const TOTAL_TIME_LIMIT = 16

export {
  TOGRA_BLUE_LABEL,
  QUESTIONS,
  ANSWERS,
  TOTAL_QUESTIONS,
  TOTAL_TIME_LIMIT,
}
