import { QuickNoteSectionName } from '../ui/quicknotes/constants'

enum VisitTypeEnum {
  Outpatient = 'Outpatient',
  EdVisit = 'EdVisit',
  TransitionalCare = 'TransitionalCare',
  IndividualPsychotherapy = 'IndividualPsychotherapy',
  FamilyPsychotherapy = 'FamilyPsychotherapy',
  Ect = 'Ect',
  Tms = 'Tms',
  Spravato = 'Spravato',
  HospitalCareInitial = 'HospitalCare/Initial',
  HospitalCareSubsequent = 'HospitalCare/Subsequent',
  HospitalCareDischarge = 'HospitalCare/Discharge',
  HospitalCareInitialDischarge = 'HospitalCare/InitialDischarge',
}

const saveAbleWdgets: QuickNoteSectionName[] = [
  QuickNoteSectionName.QuicknoteSectionHPI,
  QuickNoteSectionName.QuickNoteSectionPastPsychHx,
  QuickNoteSectionName.QuickNoteSectionPastMedicalHx,
  QuickNoteSectionName.QuickNoteSectionFamilyPsychHx,
  QuickNoteSectionName.QuickNoteSectionSocialHx,
  QuickNoteSectionName.QuickNoteSectionSubstanceUseHx,
  QuickNoteSectionName.QuicknoteSectionReviewOfSystem,
  QuickNoteSectionName.QuicknoteSectionPhysicalExam,
  QuickNoteSectionName.QuicknoteSectionMse,
  QuickNoteSectionName.QuicknoteSectionPsychiatryAssessmentPlan,
  QuickNoteSectionName.Addon,
  QuickNoteSectionName.QuicknoteSectionCodes,
]

const visitTypeToWidgets: Record<VisitTypeEnum, QuickNoteSectionName[]> = {
  [VisitTypeEnum.Outpatient]: [
    QuickNoteSectionName.QuicknoteSectionHPI,
    QuickNoteSectionName.QuickNoteSectionPastPsychHx,
    QuickNoteSectionName.QuickNoteSectionPastMedicalHx,
    QuickNoteSectionName.QuickNoteSectionFamilyPsychHx,
    QuickNoteSectionName.QuickNoteSectionSocialHx,
    QuickNoteSectionName.QuickNoteSectionSubstanceUseHx,
    QuickNoteSectionName.QuicknoteSectionPatientAllergies,
    QuickNoteSectionName.QuicknoteSectionQuestionnaires,
    QuickNoteSectionName.QuicknoteSectionReviewOfSystem,
    QuickNoteSectionName.Vitals,
    QuickNoteSectionName.QuicknoteSectionPhysicalExam,
    QuickNoteSectionName.QuicknoteSectionMse,
    QuickNoteSectionName.QuickNoteSectionDiagnosis,
    QuickNoteSectionName.QuicknoteSectionPsychiatryAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionTherapyAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionFamilyInternalMedicineAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionUploadedDocuments,
    QuickNoteSectionName.Addon,
    QuickNoteSectionName.QuicknoteSectionMedications,
    QuickNoteSectionName.QuicknoteSectionReferrals,
    QuickNoteSectionName.FollowUps,
    QuickNoteSectionName.QuicknoteSectionCodes,
  ],
  [VisitTypeEnum.EdVisit]: [
    QuickNoteSectionName.QuicknoteSectionHPI,
    QuickNoteSectionName.QuickNoteSectionPastPsychHx,
    QuickNoteSectionName.QuickNoteSectionPastMedicalHx,
    QuickNoteSectionName.QuickNoteSectionFamilyPsychHx,
    QuickNoteSectionName.QuickNoteSectionSocialHx,
    QuickNoteSectionName.QuickNoteSectionSubstanceUseHx,
    QuickNoteSectionName.QuicknoteSectionPatientAllergies,
    QuickNoteSectionName.QuicknoteSectionQuestionnaires,
    QuickNoteSectionName.QuicknoteSectionReviewOfSystem,
    QuickNoteSectionName.Vitals,
    QuickNoteSectionName.QuicknoteSectionPhysicalExam,
    QuickNoteSectionName.QuicknoteSectionMse,
    QuickNoteSectionName.QuickNoteSectionDiagnosis,
    QuickNoteSectionName.QuicknoteSectionPsychiatryAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionTherapyAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionFamilyInternalMedicineAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionUploadedDocuments,
    QuickNoteSectionName.Addon,
    QuickNoteSectionName.QuicknoteSectionMedications,
    QuickNoteSectionName.QuicknoteSectionReferrals,
    QuickNoteSectionName.FollowUps,
    QuickNoteSectionName.QuicknoteSectionCodes,
  ],
  [VisitTypeEnum.TransitionalCare]: [
    QuickNoteSectionName.QuicknoteSectionHPI,
    QuickNoteSectionName.QuickNoteSectionPastPsychHx,
    QuickNoteSectionName.QuickNoteSectionPastMedicalHx,
    QuickNoteSectionName.QuickNoteSectionFamilyPsychHx,
    QuickNoteSectionName.QuickNoteSectionSocialHx,
    QuickNoteSectionName.QuickNoteSectionSubstanceUseHx,
    QuickNoteSectionName.QuicknoteSectionPatientAllergies,
    QuickNoteSectionName.QuicknoteSectionQuestionnaires,
    QuickNoteSectionName.QuicknoteSectionReviewOfSystem,
    QuickNoteSectionName.Vitals,
    QuickNoteSectionName.QuicknoteSectionPhysicalExam,
    QuickNoteSectionName.QuicknoteSectionMse,
    QuickNoteSectionName.QuickNoteSectionDiagnosis,
    QuickNoteSectionName.QuicknoteSectionPsychiatryAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionTherapyAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionFamilyInternalMedicineAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionTcm,
    QuickNoteSectionName.QuicknoteSectionUploadedDocuments,
    QuickNoteSectionName.Addon,
    QuickNoteSectionName.QuicknoteSectionMedications,
    QuickNoteSectionName.QuicknoteSectionReferrals,
    QuickNoteSectionName.FollowUps,
    QuickNoteSectionName.QuicknoteSectionCodes,
  ],
  [VisitTypeEnum.IndividualPsychotherapy]: [
    QuickNoteSectionName.QuicknoteSectionHPI,
    QuickNoteSectionName.QuickNoteSectionPastPsychHx,
    QuickNoteSectionName.QuickNoteSectionFamilyPsychHx,
    QuickNoteSectionName.QuickNoteSectionSocialHx,
    QuickNoteSectionName.QuickNoteSectionSubstanceUseHx,
    QuickNoteSectionName.QuicknoteSectionQuestionnaires,
    QuickNoteSectionName.QuicknoteSectionMse,
    QuickNoteSectionName.QuickNoteSectionDiagnosis,
    QuickNoteSectionName.QuickNoteSectionIndividualTherapy,
    QuickNoteSectionName.QuicknoteSectionPsychiatryAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionTherapyAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionFamilyInternalMedicineAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionUploadedDocuments,
    QuickNoteSectionName.Addon,
    QuickNoteSectionName.QuicknoteSectionReferrals,
    QuickNoteSectionName.FollowUps,
    QuickNoteSectionName.QuicknoteSectionCodes,
  ],
  [VisitTypeEnum.FamilyPsychotherapy]: [
    QuickNoteSectionName.QuicknoteSectionHPI,
    QuickNoteSectionName.QuickNoteSectionPastPsychHx,
    QuickNoteSectionName.QuickNoteSectionFamilyPsychHx,
    QuickNoteSectionName.QuickNoteSectionSocialHx,
    QuickNoteSectionName.QuickNoteSectionSubstanceUseHx,
    QuickNoteSectionName.QuicknoteSectionQuestionnaires,
    QuickNoteSectionName.QuicknoteSectionMse,
    QuickNoteSectionName.QuickNoteSectionDiagnosis,
    QuickNoteSectionName.QuickNoteSectionFamilyTherapy,
    QuickNoteSectionName.QuicknoteSectionPsychiatryAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionTherapyAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionFamilyInternalMedicineAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionUploadedDocuments,
    QuickNoteSectionName.Addon,
    QuickNoteSectionName.QuicknoteSectionReferrals,
    QuickNoteSectionName.FollowUps,
    QuickNoteSectionName.QuicknoteSectionCodes,
  ],
  [VisitTypeEnum.Ect]: [
    QuickNoteSectionName.QuicknoteSectionProcedureEtcTab,
    QuickNoteSectionName.QuickNoteSectionDiagnosis,
    QuickNoteSectionName.QuicknoteSectionReferrals,
    QuickNoteSectionName.FollowUps,
    QuickNoteSectionName.QuicknoteSectionCodes,
    QuickNoteSectionName.QuicknoteSectionUploadedDocuments,
  ],
  [VisitTypeEnum.Tms]: [
    QuickNoteSectionName.ProcedureTMS,
    QuickNoteSectionName.QuickNoteSectionDiagnosis,
    QuickNoteSectionName.QuicknoteSectionCodes,
    QuickNoteSectionName.QuicknoteSectionUploadedDocuments,
  ],
  [VisitTypeEnum.Spravato]: [
    QuickNoteSectionName.QuicknoteSectionProcedureSpravato,
    QuickNoteSectionName.QuicknoteSectionUploadedDocuments,
    QuickNoteSectionName.QuickNoteSectionDiagnosis,
    QuickNoteSectionName.FollowUps,
    QuickNoteSectionName.QuicknoteSectionMedications,
    QuickNoteSectionName.Addon,
    QuickNoteSectionName.QuicknoteSectionCodes,
  ],
  [VisitTypeEnum.HospitalCareInitial]: [
    QuickNoteSectionName.QuicknoteSectionHPI,
    QuickNoteSectionName.QuickNoteSectionPastPsychHx,
    QuickNoteSectionName.QuickNoteSectionPastMedicalHx,
    QuickNoteSectionName.QuickNoteSectionFamilyPsychHx,
    QuickNoteSectionName.QuickNoteSectionSocialHx,
    QuickNoteSectionName.QuickNoteSectionSubstanceUseHx,
    QuickNoteSectionName.QuicknoteSectionPatientAllergies,
    QuickNoteSectionName.QuicknoteSectionQuestionnaires,
    QuickNoteSectionName.QuicknoteSectionReviewOfSystem,
    QuickNoteSectionName.Vitals,
    QuickNoteSectionName.QuicknoteSectionPhysicalExam,
    QuickNoteSectionName.QuicknoteSectionMse,
    QuickNoteSectionName.QuickNoteSectionDiagnosis,
    QuickNoteSectionName.QuickNoteSectionHospitalInitial,
    QuickNoteSectionName.QuicknoteSectionPsychiatryAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionTherapyAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionFamilyInternalMedicineAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionUploadedDocuments,
    QuickNoteSectionName.Addon,
    QuickNoteSectionName.QuickNoteSectionHospitalOrders,
    QuickNoteSectionName.QuicknoteSectionReferrals,
    QuickNoteSectionName.QuicknoteSectionCodes,
  ],
  [VisitTypeEnum.HospitalCareSubsequent]: [
    QuickNoteSectionName.QuicknoteSectionHPI,
    QuickNoteSectionName.QuickNoteSectionPastPsychHx,
    QuickNoteSectionName.QuickNoteSectionPastMedicalHx,
    QuickNoteSectionName.QuickNoteSectionFamilyPsychHx,
    QuickNoteSectionName.QuickNoteSectionSocialHx,
    QuickNoteSectionName.QuickNoteSectionSubstanceUseHx,
    QuickNoteSectionName.QuicknoteSectionPatientAllergies,
    QuickNoteSectionName.QuicknoteSectionQuestionnaires,
    QuickNoteSectionName.QuicknoteSectionReviewOfSystem,
    QuickNoteSectionName.Vitals,
    QuickNoteSectionName.QuicknoteSectionPhysicalExam,
    QuickNoteSectionName.QuicknoteSectionMse,
    QuickNoteSectionName.QuickNoteSectionDiagnosis,
    QuickNoteSectionName.QuickNoteSectionHospitalInitial,
    QuickNoteSectionName.QuicknoteSectionPsychiatryAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionTherapyAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionFamilyInternalMedicineAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionUploadedDocuments,
    QuickNoteSectionName.Addon,
    QuickNoteSectionName.QuickNoteSectionHospitalOrders,
    QuickNoteSectionName.QuicknoteSectionReferrals,
    QuickNoteSectionName.QuicknoteSectionCodes,
  ],
  [VisitTypeEnum.HospitalCareDischarge]: [
    QuickNoteSectionName.QuicknoteSectionAdmittingDiagnosis,
    QuickNoteSectionName.QuicknoteSectionWorkingDischargeDiagnosis,
    QuickNoteSectionName.QuicknoteSectionHPI,
    QuickNoteSectionName.QuickNoteSectionPastPsychHx,
    QuickNoteSectionName.QuickNoteSectionPastMedicalHx,
    QuickNoteSectionName.QuickNoteSectionFamilyPsychHx,
    QuickNoteSectionName.QuickNoteSectionSocialHx,
    QuickNoteSectionName.QuickNoteSectionSubstanceUseHx,
    QuickNoteSectionName.QuicknoteSectionPatientAllergies,
    QuickNoteSectionName.QuicknoteSectionQuestionnaires,
    QuickNoteSectionName.Vitals,
    QuickNoteSectionName.QuicknoteSectionPhysicalExam,
    QuickNoteSectionName.QuicknoteSectionMse,
    QuickNoteSectionName.QuicknoteSectionHospitalDischarge,
    QuickNoteSectionName.QuicknoteSectionPsychiatryAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionTherapyAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionFamilyInternalMedicineAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionUploadedDocuments,
    QuickNoteSectionName.Addon,
    QuickNoteSectionName.QuickNoteSectionHospitalOrders,
    QuickNoteSectionName.QuicknoteSectionReferrals,
    QuickNoteSectionName.FollowUps,
    QuickNoteSectionName.QuicknoteSectionCodes,
  ],
  [VisitTypeEnum.HospitalCareInitialDischarge]: [
    QuickNoteSectionName.QuicknoteSectionHPI,
    QuickNoteSectionName.QuickNoteSectionPastPsychHx,
    QuickNoteSectionName.QuickNoteSectionPastMedicalHx,
    QuickNoteSectionName.QuickNoteSectionFamilyPsychHx,
    QuickNoteSectionName.QuickNoteSectionSocialHx,
    QuickNoteSectionName.QuickNoteSectionSubstanceUseHx,
    QuickNoteSectionName.QuicknoteSectionPatientAllergies,
    QuickNoteSectionName.QuicknoteSectionQuestionnaires,
    QuickNoteSectionName.QuicknoteSectionReviewOfSystem,
    QuickNoteSectionName.Vitals,
    QuickNoteSectionName.QuicknoteSectionPhysicalExam,
    QuickNoteSectionName.QuicknoteSectionMse,
    QuickNoteSectionName.QuickNoteSectionDiagnosis,
    QuickNoteSectionName.QuickNoteSectionHospitalInitial,
    QuickNoteSectionName.QuicknoteSectionHospitalDischarge,
    QuickNoteSectionName.QuicknoteSectionPsychiatryAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionTherapyAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionFamilyInternalMedicineAssessmentPlan,
    QuickNoteSectionName.QuicknoteSectionUploadedDocuments,
    QuickNoteSectionName.Addon,
    QuickNoteSectionName.QuickNoteSectionHospitalOrders,
    QuickNoteSectionName.QuicknoteSectionReferrals,
    QuickNoteSectionName.FollowUps,
    QuickNoteSectionName.QuicknoteSectionCodes,
  ],
}
export { visitTypeToWidgets, saveAbleWdgets, VisitTypeEnum }
