name: Migrate Image from Stage to Prod

on:
  workflow_call:
    inputs:
      environment:
        description: Deployment Environment
        type: string
        required: true
      image_name:
        description: Name of image to migrate
        type: string
        required: true
      image_tag:
        description: Tag of image to migrate
        type: string
        required: true

jobs:
  migrate_image:
    permissions:
      actions: read
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.31'

      - uses: azure/login@v2
        name: Azure login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AKS_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Pull image from staging and push to prod
        run: |
          az acr login -n stgcrppluseus
          docker pull ${{ secrets.STG_ACR_NAME }}.azurecr.io/ui-${{ inputs.image_name }}:${{ inputs.image_tag }}
          docker tag ${{ secrets.STG_ACR_NAME }}.azurecr.io/ui-${{ inputs.image_name }}:${{ inputs.image_tag }} ${{ secrets.ACR_NAME }}.azurecr.io/ui-${{ inputs.image_name }}:${{ inputs.image_tag }}
          az acr login -n prodcrppluseus
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/ui-${{ inputs.image_name }}:${{ inputs.image_tag }}
