name: Manually Deploy On-Demand Environment Against PR Number
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true

jobs:
  build-configuration:
    uses: ./.github/workflows/subtaskEnvSettingsOde.yml
    with:
      pull_request_id: ${{ github.event.inputs.pr_number }}

  configure_ode_namespace:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: [build-configuration]
    uses: ./.github/workflows/subtaskSetupNamespaceOde.yml
    with:
      environment: development
      pull_request_id: ${{ github.event.inputs.pr_number }}
      env_namespace: ${{ needs.build-configuration.outputs.env_namespace }}
    secrets: inherit

  build_push_platform:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: [build-configuration, configure_ode_namespace]
    uses: ./.github/workflows/subtaskBuildPushImage.yml
    with:
      environment: development
      project: platform
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
    secrets: inherit

  build_push_clinical:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: [build-configuration, configure_ode_namespace]
    uses: ./.github/workflows/subtaskBuildPushImage.yml
    with:
      environment: development
      project: clinical
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
    secrets: inherit

  build_push_patient:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: [build-configuration, configure_ode_namespace]
    uses: ./.github/workflows/subtaskBuildPushImage.yml
    with:
      environment: development
      project: patient
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
    secrets: inherit

  build_push_galaxy:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: [build-configuration, configure_ode_namespace]
    uses: ./.github/workflows/subtaskBuildPushImage.yml
    with:
      environment: development
      project: galaxy
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
    secrets: inherit

  build_push_revcycle:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: [build-configuration, configure_ode_namespace]
    uses: ./.github/workflows/subtaskBuildPushImage.yml
    with:
      environment: development
      project: revcycle
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
    secrets: inherit

  deploy_platform:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: [build-configuration, build_push_platform]
    uses: ./.github/workflows/subtaskDeployHelmChart.yml
    with:
      environment: development
      project: platform
      helm_chart_version: ${{ needs.build-configuration.outputs.build_version }}
      helm_app_version: ${{ needs.build-configuration.outputs.build_full_version }}
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
      env_namespace: ${{ needs.build-configuration.outputs.env_namespace }}
      ingress_url: ui-pr-${{ github.event.inputs.pr_number }}.ode.psychplus.dev
    secrets: inherit

  deploy_clinical:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: [build-configuration, build_push_clinical]
    uses: ./.github/workflows/subtaskDeployHelmChart.yml
    with:
      environment: development
      project: clinical
      helm_chart_version: ${{ needs.build-configuration.outputs.build_version }}
      helm_app_version: ${{ needs.build-configuration.outputs.build_full_version }}
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
      env_namespace: ${{ needs.build-configuration.outputs.env_namespace }}
      ingress_url: ui-pr-${{ github.event.inputs.pr_number }}.ode.psychplus.dev
    secrets: inherit

  deploy_patient:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: [build-configuration, build_push_patient]
    uses: ./.github/workflows/subtaskDeployHelmChart.yml
    with:
      environment: development
      project: patient
      helm_chart_version: ${{ needs.build-configuration.outputs.build_version }}
      helm_app_version: ${{ needs.build-configuration.outputs.build_full_version }}
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
      env_namespace: ${{ needs.build-configuration.outputs.env_namespace }}
      ingress_url: ui-pr-${{ github.event.inputs.pr_number }}.ode.psychplus.dev
    secrets: inherit

  deploy_galaxy:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: [build-configuration, build_push_galaxy]
    uses: ./.github/workflows/subtaskDeployHelmChart.yml
    with:
      environment: development
      project: galaxy
      helm_chart_version: ${{ needs.build-configuration.outputs.build_version }}
      helm_app_version: ${{ needs.build-configuration.outputs.build_full_version }}
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
      env_namespace: ${{ needs.build-configuration.outputs.env_namespace }}
      ingress_url: ui-pr-${{ github.event.inputs.pr_number }}.ode.psychplus.dev
    secrets: inherit

  deploy_revcycle:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: [build-configuration, build_push_revcycle]
    uses: ./.github/workflows/subtaskDeployHelmChart.yml
    with:
      environment: development
      project: revcycle
      helm_chart_version: ${{ needs.build-configuration.outputs.build_version }}
      helm_app_version: ${{ needs.build-configuration.outputs.build_full_version }}
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
      env_namespace: ${{ needs.build-configuration.outputs.env_namespace }}
      ingress_url: ui-pr-${{ github.event.inputs.pr_number }}.ode.psychplus.dev
    secrets: inherit

  patient_portal_regression_test:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: [build-configuration, deploy_patient]
    uses: ./.github/workflows/runPatientPortalRegressionTest.yml
    with:
      environment: development
      domain: https://ui-pr-${{ github.event.inputs.pr_number }}.ode.psychplus.dev
    secrets: inherit