name: Build and Deploy ChangeHealth on Version Tag

on:
  push:
    tags:
      - 'v-[0-9]+.[0-9]+.[0-9]+-changehealth'

jobs:
  build_variables:
    runs-on: ubuntu-latest
    environment: production
    outputs:
      image_tag: ${{ steps.build_variables.outputs.image_tag }}
      build_version: ${{ steps.build_variables.outputs.build_version }}
      build_full_version: ${{ steps.build_variables.outputs.build_full_version }}
    steps:
      - name: Extract Tag Name
        id: build_variables
        run: |
          tag_ref='${{ github.ref }}'
          tag_name=$(echo "$tag_ref" | sed 's|refs/tags/||')
          tag_name="${tag_name:2}"
          echo "Tag Name: $tag_name"
          build_ci_counter="$GITHUB_RUN_NUMBER"
          build_unique_id=$(date +%Y%m%d%H%M%S%N)
          build_version=$tag_name
          build_full_version="$build_version+$build_ci_counter.$build_unique_id"
          tag_name=$(echo $tag_name | sed 's/-.*//')
          image_tag="v-$tag_name"
          echo "Tag Name: $image_tag"
          echo "image_tag=$image_tag" >> "$GITHUB_OUTPUT"
          echo "build_version=$build_version" >> "$GITHUB_OUTPUT"
          echo "build_full_version=$build_full_version" >> "$GITHUB_OUTPUT"

  build_push_platform:
    needs: [build_variables]
    uses: ./.github/workflows/subtaskBuildPushImage.yml
    with:
      environment: production
      project: platform
      image_tag: ${{ needs.build_variables.outputs.image_tag }}
    secrets: inherit

  build_push_clinical:
    needs: [build_variables]
    uses: ./.github/workflows/subtaskBuildPushImage.yml
    with:
      environment: production
      project: clinical
      image_tag: ${{ needs.build_variables.outputs.image_tag }}
    secrets: inherit

  build_push_patient:
    needs: [build_variables]
    uses: ./.github/workflows/subtaskBuildPushImage.yml
    with:
      environment: production
      project: patient
      image_tag: ${{ needs.build_variables.outputs.image_tag }}
    secrets: inherit

  build_push_revcycle:
    needs: [build_variables]
    uses: ./.github/workflows/subtaskBuildPushImage.yml
    with:
      environment: production
      project: revcycle
      image_tag: ${{ needs.build_variables.outputs.image_tag }}
    secrets: inherit

  deploy_platform:
    needs: [build_variables, build_push_platform]
    uses: ./.github/workflows/subtaskDeployHelmChart.yml
    with:
      environment: production
      project: platform
      helm_chart_version: ${{ needs.build_variables.outputs.build_version }}
      helm_app_version: ${{ needs.build_variables.outputs.build_full_version }}
      image_tag: ${{ needs.build_variables.outputs.image_tag }}
      env_namespace: env-changehealth
      ingress_url: ui.changehealth.psychplus.io
    secrets: inherit

  deploy_clinical:
    needs: [build_variables, build_push_clinical]
    uses: ./.github/workflows/subtaskDeployHelmChart.yml
    with:
      environment: production
      project: clinical
      helm_chart_version: ${{ needs.build_variables.outputs.build_version }}
      helm_app_version: ${{ needs.build_variables.outputs.build_full_version }}
      image_tag: ${{ needs.build_variables.outputs.image_tag }}
      env_namespace: env-changehealth
      ingress_url: ui.changehealth.psychplus.io
    secrets: inherit

  deploy_patient:
    needs: [build_variables, build_push_patient]
    uses: ./.github/workflows/subtaskDeployHelmChart.yml
    with:
      environment: production
      project: patient
      helm_chart_version: ${{ needs.build_variables.outputs.build_version }}
      helm_app_version: ${{ needs.build_variables.outputs.build_full_version }}
      image_tag: ${{ needs.build_variables.outputs.image_tag }}
      env_namespace: env-changehealth
      ingress_url: ui.changehealth.psychplus.io
    secrets: inherit

  deploy_revcycle:
    needs: [build_variables, build_push_revcycle]
    uses: ./.github/workflows/subtaskDeployHelmChart.yml
    with:
      environment: production
      project: revcycle
      helm_chart_version: ${{ needs.build_variables.outputs.build_version }}
      helm_app_version: ${{ needs.build_variables.outputs.build_full_version }}
      image_tag: ${{ needs.build_variables.outputs.image_tag }}
      env_namespace: env-changehealth
      ingress_url:  ui.changehealth.psychplus.io
    secrets: inherit