name: On Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      
jobs:
  which-projects:
    if: '! github.event.pull_request.draft'

    uses: ./.github/workflows/subtaskProjectFilter.yml

  build-configuration:
    if: '! github.event.pull_request.draft'

    uses: ./.github/workflows/subtaskEnvSettingsOde.yml
    with:
      pull_request_id: ${{ github.event.pull_request.number }}

  configure_ode_namespace:
    if: '! github.event.pull_request.draft'

    uses: ./.github/workflows/subtaskSetupNamespaceOde.yml
    with:
      pull_request_id: ${{ github.event.pull_request.number }}
    secrets: inherit
    
  ode_build_push:
    if: '! github.event.pull_request.draft'

    needs: [which-projects, build-configuration, configure_ode_namespace]

    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Platform
        if: 'needs.which-projects.outputs.platform == "true"'

        uses: ./.github/workflows/subtaskBuildPushDeploy.yml
        with:
          environment: development
          project: platform
          namespace_name: ${{ needs.build-configuration.outputs.env_namespace }}
          image_tag: ${{ needs.build-configuration.outputs.image_tag }}
          build_configuration: ${{ needs.build-configuration.outputs.build_configuration }}
          build_version_prefix: ${{ needs.build-configuration.outputs.build_version_prefix }}
          build_version: ${{ needs.build-configuration.outputs.build_version }}
          build_assembly_file_version: ${{ needs.build-configuration.outputs.build_assembly_file_version }}
          build_full_version: ${{ needs.build-configuration.outputs.build_full_version }}
          deployment_namespace_suffix: ${{ needs.build-configuration.outputs.deployment_namespace_suffix }}
          deployment_url_domain: ${{ needs.build-configuration.outputs.deployment_url_domain }}
          deployment_url_subdomain: ${{ needs.build-configuration.outputs.deployment_url_subdomain }}
          should_minimize_resources_for_testing: true
          use_wildcard_safe_subdomain: true
          force: true
          secrets: inherit

      - name: Clinic
        if: 'needs.which-projects.outputs.clinic == "true"'

        uses: ./.github/workflows/subtaskBuildPushDeploy.yml
        with:
          environment: development
          project: clinic
          namespace_name: ${{ needs.build-configuration.outputs.env_namespace }}
          image_tag: ${{ needs.build-configuration.outputs.image_tag }}
          build_configuration: ${{ needs.build-configuration.outputs.build_configuration }}
          build_version_prefix: ${{ needs.build-configuration.outputs.build_version_prefix }}
          build_version: ${{ needs.build-configuration.outputs.build_version }}
          build_assembly_file_version: ${{ needs.build-configuration.outputs.build_assembly_file_version }}
          build_full_version: ${{ needs.build-configuration.outputs.build_full_version }}
          deployment_namespace_suffix: ${{ needs.build-configuration.outputs.deployment_namespace_suffix }}
          deployment_url_domain: ${{ needs.build-configuration.outputs.deployment_url_domain }}
          deployment_url_subdomain: ${{ needs.build-configuration.outputs.deployment_url_subdomain }}
          should_minimize_resources_for_testing: true
          use_wildcard_safe_subdomain: true
          force: true
          secrets: inherit

      - name: Patient
        if: 'needs.which-projects.outputs.patient == "true"'

        uses: ./.github/workflows/subtaskBuildPushDeploy.yml
        with:
          environment: development
          project: patient
          namespace_name: ${{ needs.build-configuration.outputs.env_namespace }}
          image_tag: ${{ needs.build-configuration.outputs.image_tag }}
          build_configuration: ${{ needs.build-configuration.outputs.build_configuration }}
          build_version_prefix: ${{ needs.build-configuration.outputs.build_version_prefix }}
          build_version: ${{ needs.build-configuration.outputs.build_version }}
          build_assembly_file_version: ${{ needs.build-configuration.outputs.build_assembly_file_version }}
          build_full_version: ${{ needs.build-configuration.outputs.build_full_version }}
          deployment_namespace_suffix: ${{ needs.build-configuration.outputs.deployment_namespace_suffix }}
          deployment_url_domain: ${{ needs.build-configuration.outputs.deployment_url_domain }}
          deployment_url_subdomain: ${{ needs.build-configuration.outputs.deployment_url_subdomain }}
          should_minimize_resources_for_testing: true
          use_wildcard_safe_subdomain: true
          force: true
          secrets: inherit

      - name: RevCycle
        if: 'needs.which-projects.outputs.revcycle == "true"'

        uses: ./.github/workflows/subtaskBuildPushDeploy.yml
        with:
          environment: development
          project: revcycle
          namespace_name: ${{ needs.build-configuration.outputs.env_namespace }}
          image_tag: ${{ needs.build-configuration.outputs.image_tag }}
          build_configuration: ${{ needs.build-configuration.outputs.build_configuration }}
          build_version_prefix: ${{ needs.build-configuration.outputs.build_version_prefix }}
          build_version: ${{ needs.build-configuration.outputs.build_version }}
          build_assembly_file_version: ${{ needs.build-configuration.outputs.build_assembly_file_version }}
          build_full_version: ${{ needs.build-configuration.outputs.build_full_version }}
          deployment_namespace_suffix: ${{ needs.build-configuration.outputs.deployment_namespace_suffix }}
          deployment_url_domain: ${{ needs.build-configuration.outputs.deployment_url_domain }}
          deployment_url_subdomain: ${{ needs.build-configuration.outputs.deployment_url_subdomain }}
          should_minimize_resources_for_testing: true
          use_wildcard_safe_subdomain: true
          force: true
          secrets: inherit
