name: Commit Workflow

on:
  push: 
    branches:
      - main

jobs:

  which-projects:
    uses: Psychplus/ReactUI/.github/workflows/ProjectFilter.yml@main


  test_all:
    runs-on: ubuntu-latest
    needs: which-projects
    steps:
      - uses: actions/checkout@v2
      - run: echo "PUSH- github=${{ needs.which-projects.outputs.github }} k8s=${{ needs.which-projects.outputs.k8s }} "
      - run: echo "platform=${{ needs.which-projects.outputs.platform }} clinical=${{ needs.which-projects.outputs.clinical }} patient=${{ needs.which-projects.outputs.patient }} revcycle=${{ needs.which-projects.outputs.revcycle }}"
