name: Commit Workflow

on:
  push: 
    branches:
      - main

jobs:

  which-projects:
    uses: ./.github/workflows/subtaskProjectFilter.yml


  test_all:
    runs-on: ubuntu-latest
    needs: which-projects
    steps:
      - uses: actions/checkout@v3
      - run: echo "PUSH- github=${{ needs.which-projects.outputs.github }} helm=${{ needs.which-projects.outputs.helm }} k8s=${{ needs.which-projects.outputs.k8s }}"
      - run: echo "platform=${{ needs.which-projects.outputs.platform }} clinical=${{ needs.which-projects.outputs.clinical }} patient=${{ needs.which-projects.outputs.patient }} revcycle=${{ needs.which-projects.outputs.revcycle }}"
