name: On Push Request Workflow

on:
  push:
    branches:
      - main

jobs:
  build-configuration:
    if: '! github.event.pull_request.draft'

    uses: ./.github/workflows/subtaskEnvSettingsOde.yml
    with:
      pull_request_id: 0

  test_all:
    runs-on: ubuntu-latest
    needs: [build-configuration]
    steps:
      - run: echo "PUSH- github=${{ needs.which-projects.outputs.github }} helm=${{ needs.which-projects.outputs.helm }} k8s=${{ needs.which-projects.outputs.k8s }}"
      - run: echo "patient=${{ needs.which-projects.outputs.patient }} galaxy=${{ needs.which-projects.outputs.galaxy }}"
      - run: echo "env_namespace=${{ needs.build-configuration.outputs.env_namespace }}"
