name: On Push Request Workflow

on:
  push: 
    branches:
      - main

jobs:
  build-configuration:
    if: '! github.event.pull_request.draft'

    uses: ./.github/workflows/subtaskEnvSettingsOde.yml
    with:
      pull_request_id: 0
  
  test_all:
    runs-on: ubuntu-latest
    needs: [build-configuration]
    steps:
      - run: echo "PUSH- github=${{ needs.which-projects.outputs.github }} helm=${{ needs.which-projects.outputs.helm }} k8s=${{ needs.which-projects.outputs.k8s }}"
      - run: echo "platform=${{ needs.which-projects.outputs.platform }} clinical=${{ needs.which-projects.outputs.clinical }} patient=${{ needs.which-projects.outputs.patient }} revcycle=${{ needs.which-projects.outputs.revcycle }}"
      - run: echo "env_namespace=${{ needs.build-configuration.outputs.env_namespace }}"

  test_login:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [build-configuration]

    steps:
      - uses: actions/checkout@v4

      - uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.31'

      - uses: azure/login@v2
        name: Azure login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AKS_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - uses: Azure/aks-set-context@v3
        name: Get K8s context
        with:
          cluster-name: ${{ secrets.AKS_NAME }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          admin: false
          use-kubelogin: true
