name: on Pull Request Workflow
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  build-configuration:
    uses: ./.github/workflows/subtaskEnvSettingsOde.yml
    with:
      pull_request_id: ${{ github.event.pull_request.number }}

  configure_ode_namespace:
    needs: [build-configuration]
    uses: ./.github/workflows/subtaskSetupNamespaceOde.yml
    with:
      environment: development
      pull_request_id: ${{ github.event.pull_request.number }}
      env_namespace: ${{ needs.build-configuration.outputs.env_namespace }}
    secrets: inherit

  build_push_platform:
    needs: [build-configuration, configure_ode_namespace]
    uses: ./.github/workflows/subtaskBuildPushImage.yml
    with:
      environment: development
      project: platform
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
    secrets: inherit

  build_push_clinical:
    needs: [build-configuration, configure_ode_namespace]
    uses: ./.github/workflows/subtaskBuildPushImage.yml
    with:
      environment: development
      project: clinical
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
    secrets: inherit

  build_push_patient:
    needs: [build-configuration, configure_ode_namespace]
    uses: ./.github/workflows/subtaskBuildPushImage.yml
    with:
      environment: development
      project: patient
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
    secrets: inherit

  build_push_galaxy:
    needs: [build-configuration, configure_ode_namespace]
    uses: ./.github/workflows/subtaskBuildPushImage.yml
    with:
      environment: development
      project: galaxy
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
    secrets: inherit

  build_push_revcycle:
    needs: [build-configuration, configure_ode_namespace]
    uses: ./.github/workflows/subtaskBuildPushImage.yml
    with:
      environment: development
      project: revcycle
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
    secrets: inherit

  deploy_platform:
    needs: [build-configuration, build_push_platform]
    uses: ./.github/workflows/subtaskDeployHelmChart.yml
    with:
      environment: development
      project: platform
      helm_chart_version: ${{ needs.build-configuration.outputs.build_version }}
      helm_app_version: ${{ needs.build-configuration.outputs.build_full_version }}
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
      env_namespace: ${{ needs.build-configuration.outputs.env_namespace }}
      ingress_url: ui-pr-${{ github.event.pull_request.number }}.ode.psychplus.dev
      autoscaling_min_replicas: 1
      autoscaling_max_replicas: 1
    secrets: inherit

  deploy_clinical:
    needs: [build-configuration, build_push_clinical]
    uses: ./.github/workflows/subtaskDeployHelmChart.yml
    with:
      environment: development
      project: clinical
      helm_chart_version: ${{ needs.build-configuration.outputs.build_version }}
      helm_app_version: ${{ needs.build-configuration.outputs.build_full_version }}
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
      env_namespace: ${{ needs.build-configuration.outputs.env_namespace }}
      ingress_url: ui-pr-${{ github.event.pull_request.number }}.ode.psychplus.dev
      autoscaling_min_replicas: 1
      autoscaling_max_replicas: 1
    secrets: inherit

  deploy_patient:
    needs: [build-configuration, build_push_patient]
    uses: ./.github/workflows/subtaskDeployHelmChart.yml
    with:
      environment: development
      project: patient
      helm_chart_version: ${{ needs.build-configuration.outputs.build_version }}
      helm_app_version: ${{ needs.build-configuration.outputs.build_full_version }}
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
      env_namespace: ${{ needs.build-configuration.outputs.env_namespace }}
      ingress_url: ui-pr-${{ github.event.pull_request.number }}.ode.psychplus.dev
      autoscaling_min_replicas: 1
      autoscaling_max_replicas: 1
    secrets: inherit

  deploy_galaxy:
    needs: [build-configuration, build_push_galaxy]
    uses: ./.github/workflows/subtaskDeployHelmChart.yml
    with:
      environment: development
      project: galaxy
      helm_chart_version: ${{ needs.build-configuration.outputs.build_version }}
      helm_app_version: ${{ needs.build-configuration.outputs.build_full_version }}
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
      env_namespace: ${{ needs.build-configuration.outputs.env_namespace }}
      ingress_url: ui-pr-${{ github.event.pull_request.number }}.ode.psychplus.dev
      autoscaling_min_replicas: 1
      autoscaling_max_replicas: 1
    secrets: inherit

  deploy_revcycle:
    needs: [build-configuration, build_push_revcycle]
    uses: ./.github/workflows/subtaskDeployHelmChart.yml
    with:
      environment: development
      project: revcycle
      helm_chart_version: ${{ needs.build-configuration.outputs.build_version }}
      helm_app_version: ${{ needs.build-configuration.outputs.build_full_version }}
      image_tag: ${{ needs.build-configuration.outputs.image_tag }}
      env_namespace: ${{ needs.build-configuration.outputs.env_namespace }}
      ingress_url: ui-pr-${{ github.event.pull_request.number }}.ode.psychplus.dev
      autoscaling_min_replicas: 1
      autoscaling_max_replicas: 1
    secrets: inherit

