name: Deploy Release To Production

on:
  push:
    tags:
      - 'v-[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_variables:
    runs-on: ubuntu-latest
    environment: production
    outputs:
      image_tag: ${{ steps.build_variables.outputs.image_tag }}
      build_version: ${{ steps.build_variables.outputs.build_version }}
      build_full_version: ${{ steps.build_variables.outputs.build_full_version }}
    steps:
      - name: Extract Tag Name
        id: build_variables
        run: |
          tag_ref='${{ github.ref }}'
          tag_name=$(echo "$tag_ref" | sed 's|refs/tags/||')
          tag_name="${tag_name:2}"
          echo "Tag Name: $tag_name"
          build_ci_counter="$GITHUB_RUN_NUMBER"
          build_unique_id=$(date +%Y%m%d%H%M%S%N)
          build_version=$tag_name
          build_full_version="$build_version+$build_ci_counter.$build_unique_id"
          image_tag="v-$build_version"
          echo "image_tag=$image_tag" >> "$GITHUB_OUTPUT"
          echo "build_version=$build_version" >> "$GITHUB_OUTPUT"
          echo "build_full_version=$build_full_version" >> "$GITHUB_OUTPUT"

  migrate_patient_image:
    needs: build_variables
    uses: ./.github/workflows/MigrateImageFromStageToProd.yml
    with:
      environment: production
      image_name: patient
      image_tag: ${{ needs.build_variables.outputs.image_tag }}
    secrets: inherit

  migrate_galaxy_image:
    needs: build_variables
    uses: ./.github/workflows/MigrateImageFromStageToProd.yml
    with:
      environment: production
      image_name: galaxy
      image_tag: ${{ needs.build_variables.outputs.image_tag }}
    secrets: inherit

  deploy_patient:
    needs: [build_variables, migrate_patient_image]
    uses: ./.github/workflows/subtaskDeployHelmChart.yml
    with:
      environment: production
      project: patient
      helm_chart_version: ${{ needs.build_variables.outputs.build_version }}
      helm_app_version: ${{ needs.build_variables.outputs.build_full_version }}
      image_tag: ${{ needs.build_variables.outputs.image_tag }}
      env_namespace: env-ehr
      ingress_url: ui.psychplus.io
    secrets: inherit

  deploy_galaxy:
    needs: [build_variables, migrate_galaxy_image]
    uses: ./.github/workflows/subtaskDeployHelmChart.yml
    with:
      environment: production
      project: galaxy
      helm_chart_version: ${{ needs.build_variables.outputs.build_version }}
      helm_app_version: ${{ needs.build_variables.outputs.build_full_version }}
      image_tag: ${{ needs.build_variables.outputs.image_tag }}
      env_namespace: env-ehr
      ingress_url: ui.psychplus.io
    secrets: inherit

  publish_release:
    runs-on: ubuntu-latest
    environment: staging
    needs:
      - deploy_patient
      - deploy_galaxy
    steps:
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
