name: Which Project(s)

on:
  workflow_call:
    outputs:
      github:
        description: "Is github action changed"
        value: ${{ jobs.paths-filter.outputs.github }}

        k8s:
        description: "Is k8s helm changed"
        value: ${{ jobs.paths-filter.outputs.k8s }}

        platform:
        description: "Is platform build"
        value: ${{ jobs.paths-filter.outputs.platform }}

      clinical:
        description: "Is clinical build"
        value: ${{ jobs.paths-filter.outputs.clinical }}

      patient:
        description: "Is patient build"
        value: ${{ jobs.paths-filter.outputs.patient }}

      revcycle:
        description: "Is revcycle build"
        value: ${{ jobs.paths-filter.outputs.revcycle }}
    
jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      github: ${{ steps.filter.outputs.github}}
      k8s: ${{ steps.filter.outputs.k8s}}
      platform: ${{ steps.filter.outputs.platform}}
      clinical: ${{ steps.filter.outputs.clinical}}
      patient: ${{ steps.filter.outputs.patient}}
      revcycle: ${{ steps.filter.outputs.revcycle}}

    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            github:
              - '.github/**'
            k8s:
              - 'k8s/**'
            platform:
              - 'apps/platform/**'
              - 'apps/api/**'
            clinical:
              - 'apps/clinical/**'
            patient:
              - 'apps/patient/**'
            revcycle:
              - 'apps/revcycle/**'
