name: Subtask Determine Which Project(s)

on:
  workflow_call:
    outputs:
      github:
        description: "Is github workflows changed"
        value: ${{ jobs.paths-filter.outputs.github }}

      helm:
        description: "Is helm changed"
        value: ${{ jobs.paths-filter.outputs.helm }}
  
      k8s:
        description: "Is k8s changed"
        value: ${{ jobs.paths-filter.outputs.k8s }}
    
      platform:
        description: "Is platform build"
        value: ${{ jobs.paths-filter.outputs.platform }}

      clinical:
        description: "Is clinical build"
        value: ${{ jobs.paths-filter.outputs.clinical }}

      patient:
        description: "Is patient build"
        value: ${{ jobs.paths-filter.outputs.patient }}

      revcycle:
        description: "Is revcycle build"
        value: ${{ jobs.paths-filter.outputs.revcycle }}
    
jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      github: ${{ steps.filter.outputs.github}}
      helm: ${{ steps.filter.outputs.helm}}
      k8s: ${{ steps.filter.outputs.k8s}}
      platform: ${{ steps.filter.outputs.platform}}
      clinical: ${{ steps.filter.outputs.clinical}}
      patient: ${{ steps.filter.outputs.patient}}
      revcycle: ${{ steps.filter.outputs.revcycle}}

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            github:
              - '.github/**'
            helm:
              - 'ui-chart/**'
            k8s:
              - 'k8s/**'
            platform:
              - 'apps/platform/**'
              - 'apps/api/**'
              - 'environments/dev/platform/**'
            clinical:
              - 'apps/clinical/**'
              - 'environments/dev/clinical/**' 
            patient:
              - 'apps/patient/**'
              - 'environments/dev/patient/**'
            revcycle:
              - 'apps/revcycle/**'
              - 'environments/dev/revcycle/**'
