name: Subtask Remove Namespace for On-Demand Environment (ODE)

on:
  workflow_dispatch:
    inputs:
      namespace_name:
        description: Name for the namespace to configure as an on-demand environment
        type: string
        required: true

  workflow_call:
    inputs:
      namespace_name:
        description: Name for the namespace to configure as an on-demand environment
        type: string
        required: true

jobs:
  delete_ode_namespace_if_exists:
    permissions:
      actions: read
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.31'

      - uses: azure/login@v2
        name: Azure login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AKS_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - uses: Azure/aks-set-context@v3
        name: Get K8s context
        with:
          cluster-name: ${{ secrets.AKS_NAME }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          admin: false
          use-kubelogin: true

      - name: Remove namespace if it exists
        timeout-minutes: 5
        run: |
          if kubectl get namespace ${{ inputs.namespace_name }} ; then
            kubectl delete namespace ${{ inputs.namespace_name }} --grace-period=1
          fi
